Repository BinaryStudioAcademy/bsa-2020-TaskyHusky, pull requests merged in 2020-08, with the labels that each got.

#1 Add local and jwt authorization
  server/.env.example
  server/.eslintrc.json
  server/config/jwt.config.ts
  server/config/passport.config.ts
  server/index.ts
  server/package-lock.json
  server/package.json
  server/src/constants/auth.constants.ts
  server/src/constants/hash.constants.ts
  server/src/controllers/auth.controllers.ts
  server/src/helpers/jwt.helper.ts
  server/src/helpers/password.helper.ts
  server/src/middleware/jwt.middleware.ts
  server/src/middleware/login.middleware.ts
  server/src/middleware/register.middleware.ts
  server/src/routes/auth.routes.ts
  server/src/routes/index.ts
Labels: enhancement

#6 Move uuid to dev dependencies
  server/package.json
Labels: enhancement

#4 Add signup page
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/PasswordInput/index.tsx
  client/src/components/PrivateRoute/index.tsx
  client/src/components/PublicRoute/index.tsx
  client/src/containers/Routing/index.tsx
  client/src/containers/SignUpForm/index.tsx
  client/src/helpers/setToken.helper.ts
  client/src/index.tsx
  client/src/pages/SignUp/index.tsx
  client/src/services/auth.service.ts
  client/src/styles/index.scss
  client/src/styles/variables.scss
  client/src/typings/webapi.d.ts
  server/scripts/update_webapi.ts
  server/src/models/Result.ts
Labels: bug, enhancement

#2 Add login page
  client/src/containers/LoginPage/index.tsx
  client/src/containers/LoginPage/styles.module.scss
  client/src/containers/Routing/index.tsx
  client/src/helpers/validateEmail.helper.ts
  client/src/index.tsx
  client/src/pages/Login.tsx
Labels: enhancement

#8 Feature/error handler
  server/index.ts
  server/src/helpers/errorHandler.helper/errorHandler.helper.ts
  server/src/helpers/errorHandler.helper/httpStattusCode.helper.ts
  server/src/middleware/errorHandler.middleware.ts
Labels: enhancement

#9 Feature/filter entity
  server/package-lock.json
  server/package.json
  server/src/controllers/filter.controllers.ts
  server/src/controllers/filterDefinition.controllers.ts
  server/src/controllers/filterPart.controllers.ts
  server/src/entity/Filter.ts
  server/src/entity/FilterDefinition.ts
  server/src/entity/FilterPart.ts
  server/src/repositories/filter.repository.ts
  server/src/repositories/filterDefinition.repository.ts
  server/src/repositories/filterPart.repository.ts
  server/src/routes/filter.routes.ts
  server/src/routes/filterDefinition.routes.ts
  server/src/routes/filterPart.routes.ts
  server/src/routes/index.ts
Labels: enhancement

#11 Feature/profile page
  server/config/passport.config.ts
  server/interfaces/User.ts
  server/package-lock.json
  server/package.json
  server/src/constants/api.constants.ts
  server/src/controllers/auth.controllers.ts
  server/src/controllers/user.controllers.ts
  server/src/customDefinition/custom.d.ts
  server/src/entity/User.ts
  server/src/migration/1596468052663-User.ts
  server/src/repositories/user.repository.ts
  server/src/routes/index.ts
  server/src/routes/user.routes.ts
  server/tsconfig.json
Labels: feature

#12 move userInterface to model folder
  server/config/passport.config.ts
  server/src/models/User.ts
  server/src/repositories/user.repository.ts
Labels: feature

#10 Add issue crud
  client/src/typings/webapi.d.ts
  server/src/controllers/issue.controllers.ts
  server/src/controllers/issueType.controllers.ts
  server/src/controllers/priority.controllers.ts
  server/src/entity/Issue.ts
  server/src/entity/IssueType.ts
  server/src/entity/Priority.ts
  server/src/helpers/error.helper.ts
  server/src/repositories/issue.repository.ts
  server/src/repositories/issueType.repository.ts
  server/src/repositories/priority.repository.ts
  server/src/routes/index.ts
  server/src/routes/issue.routes.ts
  server/src/routes/issueType.routes.ts
  server/src/routes/priority.routes.ts
Labels: enhancement

#16 Fixes commit
  server/config/passport.config.ts
  server/src/helpers/errorHandler.helper/errorHandler.helper.ts
  server/src/models/Issue.ts
  server/src/repositories/user.repository.ts
Labels: enhancement

#17 Edits by comments
  server/src/constants/httpStattusCode.constants.ts
  server/src/helpers/errorHandler.helper.ts
  server/src/middleware/errorHandler.middleware.ts
Labels: help wanted

#18 Feature: CreateIssueModal
  client/src/components/common/PasswordInput/index.tsx
  client/src/components/common/TagsInput/index.tsx
  client/src/components/common/TagsInput/styles.module.scss
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/CreateIssueModal/examplePage.tsx
  client/src/containers/CreateIssueModal/index.tsx
  client/src/containers/CreateIssueModal/logic/context.tsx
  client/src/containers/CreateIssueModal/logic/initalState.ts
  client/src/containers/CreateIssueModal/logic/types.ts
  client/src/containers/Routing/index.tsx
  client/src/containers/SignUpForm/index.tsx
  client/src/helpers/callApi.helper.ts
  client/src/services/issue.service.ts
  client/src/typings/webapi.d.ts
  server/package-lock.json
Labels: enhancement, feature

#21 Add authReducer
  client/src/containers/LoginPage/index.tsx
  client/src/containers/LoginPage/logic/actionTypes.ts
  client/src/containers/LoginPage/logic/actions.ts
  client/src/containers/LoginPage/logic/reducer.ts
  client/src/containers/LoginPage/logic/saga.ts
  client/src/containers/LoginPage/logic/state.ts
  client/src/containers/Routing/index.tsx
  client/src/pages/LogIn/index.tsx
  client/src/redux/rootReducer.ts
  client/src/redux/rootSaga.ts
  client/src/services/auth.service.ts
  client/src/typings/rootState.ts
  client/src/typings/webapi.d.ts
Labels: enhancement

#23 Add firstName and lastName fields
  client/src/containers/SignUpForm/index.tsx
  client/src/services/auth.service.ts
  server/config/passport.config.ts
Labels: enhancement

#20 Feature/crud projects
  client/package.json
  client/src/assets/images/scrum.svg
  client/src/components/CreateProjectModal/index.tsx
  client/src/components/CreateProjectModal/styles.module.scss
  client/src/containers/App/App.tsx
  client/src/containers/Projects/index.tsx
  client/src/containers/Projects/logic/actionTypes.ts
  client/src/containers/Projects/logic/actions.ts
  client/src/containers/Projects/logic/reducer.ts
  client/src/containers/Projects/logic/saga.ts
  client/src/containers/Projects/logic/state.ts
  client/src/containers/Projects/styles.module.scss
  client/src/containers/Routing/index.tsx
  client/src/redux/rootReducer.ts
  client/src/redux/rootSaga.ts
  client/src/services/projects.service.ts
  client/src/styles/index.scss
  client/src/typings/rootState.ts
  client/src/typings/webapi.d.ts
  server/src/controllers/projects.controllers.ts
  server/src/entity/Projects.ts
  server/src/repositories/projects.repository.ts
  server/src/routes/index.ts
  server/src/routes/projects.routes.ts
Labels: enhancement

#24 Remove example api
  client/src/components/CreateProjectModal/index.tsx
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/CreateIssueModal/examplePage.tsx
  client/src/containers/Example/example.module.scss
  client/src/containers/Example/index.tsx
  client/src/containers/Example/logic/actionTypes.ts
  client/src/containers/Example/logic/actions.ts
  client/src/containers/Example/logic/reducer.ts
  client/src/containers/Example/logic/saga.ts
  client/src/containers/Example/logic/state.ts
  client/src/containers/LoginPage/logic/saga.ts
  client/src/containers/Projects/index.tsx
  client/src/containers/Routing/index.tsx
  client/src/containers/SignUpForm/index.tsx
  client/src/pages/CreateIssue/index.tsx
  client/src/pages/CreateIssue/logic/actionTypes.ts
  client/src/pages/CreateIssue/logic/actions.ts
  client/src/pages/CreateIssue/logic/initialState.ts
  client/src/pages/CreateIssue/logic/reducer.ts
  client/src/pages/CreateIssue/logic/saga.ts
  client/src/pages/CreateIssue/logic/types.ts
  client/src/redux/rootReducer.ts
  client/src/redux/rootSaga.ts
  client/src/services/auth.service.ts
  client/src/services/example.service.ts
  client/src/services/issue.service.ts
  client/src/styles/index.scss
  client/src/typings/rootState.ts
  client/src/typings/webapi.d.ts
  server/src/controllers/example.controllers.ts
  server/src/entity/Example.ts
  server/src/models/Issue.ts
  server/src/models/Result.ts
  server/src/repositories/example.repository.ts
  server/src/repositories/issueType.repository.ts
  server/src/routes/example.routes.ts
  server/src/routes/index.ts
Labels: enhancement

#25 Add get-by-key api
  server/src/controllers/issue.controllers.ts
  server/src/repositories/issue.repository.ts
  server/src/routes/issue.routes.ts
Labels: bug, enhancement, will update

#13 Add Header
  client/public/index.html
  client/src/components/DashboardsMenu/index.tsx
  client/src/components/FiltersMenu/index.tsx
  client/src/components/ProjectsMenu/index.tsx
  client/src/containers/Header/index.tsx
  client/src/containers/Header/styles.module.scss
  client/src/containers/Routing/index.tsx
  client/src/styles/headerDropDown.module.scss
Labels: enhancement

#27 Feature: Add filters page
  client/src/commonLogic/filterDefs/actionTypes.ts
  client/src/commonLogic/filterDefs/actions.ts
  client/src/commonLogic/filterDefs/reducer.ts
  client/src/commonLogic/filterDefs/saga.ts
  client/src/commonLogic/filterDefs/state.ts
  client/src/components/Avatar/index.tsx
  client/src/components/Avatar/styles.module.scss
  client/src/components/FilterItem/index.tsx
  client/src/components/FilterItem/styles.module.scss
  client/src/containers/Filters/headerStart.svg
  client/src/containers/Filters/index.tsx
  client/src/containers/Filters/logic/actionTypes.ts
  client/src/containers/Filters/logic/actions.ts
  client/src/containers/Filters/logic/helpers.ts
  client/src/containers/Filters/logic/reducer.ts
  client/src/containers/Filters/logic/saga.ts
  client/src/containers/Filters/logic/state.ts
  client/src/containers/Filters/styles.module.scss
  client/src/containers/Header/index.tsx
  client/src/containers/Routing/index.tsx
  client/src/pages/Filters/index.tsx
  client/src/redux/rootReducer.ts
  client/src/redux/rootSaga.ts
  client/src/services/filter.service.ts
  client/src/typings/rootState.ts
  client/src/typings/webapi.d.ts
  server/.vscode/launch.json
  server/index.ts
  server/src/controllers/filter.controllers.ts
  server/src/controllers/filterDefinition.controllers.ts
  server/src/controllers/filterPart.controllers.ts
  server/src/controllers/user.controllers.ts
  server/src/entity/Filter.ts
  server/src/entity/FilterPart.ts
  server/src/entity/User.ts
  server/src/repositories/filter.repository.ts
  server/src/repositories/filterDefinition.repository.ts
  server/src/repositories/filterPart.repository.ts
  server/src/routes/filter.routes.ts
  server/src/routes/user.routes.ts
Labels: enhancement

#34 Add IssueType and Priority seeds
  server/package.json
  server/src/seeders/1596645901833-Board.ts
  server/src/seeders/1596718071573-Priority.ts
  server/src/seeders/1596719363245-IssueType.ts
Labels: enhancement

#33 Fix column validation in User entity
  server/src/entity/User.ts
Labels: bug

#35 Fix: issue modal styles
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/Routing/index.tsx
  client/src/styles/headerDropDown.module.scss
  client/src/styles/index.scss
Labels: enhancement

#29 Feature/team page
  client/package.json
  client/src/assets/images/team-page-links.jpg
  client/src/assets/images/team-page-works.jpg
  client/src/components/TeamDevsCard/index.tsx
  client/src/components/TeamLinks/index.tsx
  client/src/components/TeamNotification/index.tsx
  client/src/components/TeamWorkedProjects/index.tsx
  client/src/components/TeamsMembersCard/index.tsx
  client/src/containers/Routing/index.tsx
  client/src/containers/TeamPage/index.tsx
  client/src/containers/TeamPage/styles.module.scss
  client/src/pages/Team/index.tsx
  client/src/services/team.service.ts
  server/src/controllers/teams.controllers.ts
  server/src/entity/Teams.ts
  server/src/entity/TeamsPeople.ts
  server/src/entity/User.ts
  server/src/models/Team.ts
  server/src/repositories/teams.repository.ts
  server/src/routes/index.ts
  server/src/routes/teams.routes.ts
  server/src/seeders/1606645895543-Teams.ts
Labels: feature

#38 Replace #app with #root
  client/src/containers/Header/styles.module.scss
Labels: bug

#41 Remove token and clear auth state on log out
  client/src/components/PrivateRoute/index.tsx
  client/src/containers/Header/index.tsx
  client/src/containers/LoginPage/index.tsx
  client/src/containers/LoginPage/logic/actionTypes.ts
  client/src/containers/LoginPage/logic/actions.ts
  client/src/containers/LoginPage/logic/reducer.ts
  client/src/containers/LoginPage/logic/saga.ts
  client/src/containers/Routing/index.tsx
  client/src/helpers/setToken.helper.ts
Labels: enhancement, feature

#31 Feature: issue page
  client/src/components/common/TagsInput/index.tsx
  client/src/components/common/TagsInput/styles.module.scss
  client/src/constants/KeyGenerate.ts
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/CreateIssueModal/logic/context.tsx
  client/src/containers/CreateIssueModal/logic/initalState.ts
  client/src/containers/Routing/index.tsx
  client/src/containers/UpdateIssueModal/index.tsx
  client/src/helpers/randomString.helper.ts
  client/src/pages/CreateIssue/index.tsx
  client/src/pages/CreateIssue/logic/actionTypes.ts
  client/src/pages/CreateIssue/logic/actions.ts
  client/src/pages/CreateIssue/logic/saga.ts
  client/src/pages/IssuePage/index.tsx
  client/src/pages/IssuePage/styles.module.scss
  client/src/services/issue.service.ts
  client/src/typings/webapi.d.ts
  server/src/models/Issue.ts
  server/src/models/Result.ts
  server/src/seeders/1596645901833-Board.ts
Labels: enhancement, feature

#37 Feature/create project
  client/src/assets/images/bug_tracking.svg
  client/src/assets/images/kanban.svg
  client/src/assets/images/scrum.svg
  client/src/components/CreateProjectModal/index.tsx
  client/src/components/CreateProjectModal/styles.module.scss
  client/src/components/common/Spinner/index.tsx
  client/src/components/common/Spinner/styles.module.scss
  client/src/containers/CreateProjectModal/index.tsx
  client/src/containers/CreateProjectModal/logic/actionTypes.ts
  client/src/containers/CreateProjectModal/logic/actions.ts
  client/src/containers/CreateProjectModal/logic/reducer.ts
  client/src/containers/CreateProjectModal/logic/saga.ts
  client/src/containers/CreateProjectModal/logic/state.ts
  client/src/containers/CreateProjectModal/styles.module.scss
  client/src/containers/Projects/index.tsx
  client/src/containers/Projects/logic/actionTypes.ts
  client/src/containers/Projects/logic/actions.ts
  client/src/containers/Projects/logic/reducer.ts
  client/src/containers/Projects/logic/saga.ts
  client/src/containers/Projects/logic/state.ts
  client/src/containers/Projects/styles.module.scss
  client/src/containers/Routing/index.tsx
  client/src/pages/Projects/index.tsx
  client/src/redux/rootReducer.ts
  client/src/redux/rootSaga.ts
  client/src/services/projects.service.ts
  client/src/typings/rootState.ts
  client/src/typings/webapi.d.ts
  server/src/controllers/projects.controllers.ts
  server/src/entity/Projects.ts
  server/src/repositories/projects.repository.ts
Labels: enhancement

#43 Fix data structure mistake
  server/src/controllers/projects.controllers.ts
Labels: fix

#42 Update AuthReducer state on new user registration
  client/src/components/PrivateRoute/index.tsx
  client/src/containers/LoginPage/logic/actionTypes.ts
  client/src/containers/LoginPage/logic/actions.ts
  client/src/containers/LoginPage/logic/reducer.ts
  client/src/containers/LoginPage/logic/saga.ts
  client/src/containers/SignUpForm/index.tsx
  client/src/typings/webapi.d.ts
Labels: enhancement, feature

#44 Feature/create project
  client/src/containers/CreateProjectModal/index.tsx
  client/src/containers/CreateProjectModal/logic/actionTypes.ts
  client/src/containers/CreateProjectModal/logic/actions.ts
  client/src/containers/CreateProjectModal/logic/reducer.ts
  client/src/containers/CreateProjectModal/logic/state.ts
  server/src/controllers/projects.controllers.ts
Labels: enhancement

#47 Refactor redirects on login page
  client/src/containers/LoginPage/index.tsx
  client/src/containers/SignUpForm/index.tsx
Labels: refactoring

#48 Move destructuring to try block
  server/src/controllers/projects.controllers.ts
Labels: bug, fix

#50 Feature/profile page
  client/package-lock.json
  client/package.json
  client/src/components/ContentInput/index.tsx
  client/src/components/ContentInput/styles.module.scss
  client/src/components/FilterItem/index.tsx
  client/src/components/PrivateRoute/index.tsx
  client/src/components/ProfileAboutBlock/index.tsx
  client/src/components/ProfileAboutItem/index.tsx
  client/src/components/ProfileAboutItem/styles.module.scss
  client/src/components/ProfileAside/index.tsx
  client/src/components/ProfileAside/styles.module.scss
  client/src/components/ProfileContactBlock/index.tsx
  client/src/components/ProfileContactBlock/styles.module.scss
  client/src/components/ProfileHeader/index.tsx
  client/src/components/ProfileHeader/styles.module.scss
  client/src/components/ProfilePicture/index.tsx
  client/src/components/ProfilePicture/styles.module.scss
  client/src/components/ProfileSection/index.tsx
  client/src/components/ProfileSection/styles.module.scss
  client/src/components/ProfileTeamBlock/index.tsx
  client/src/components/ProfileTeamBlock/styles.module.scss
  client/src/components/PublicRoute/index.tsx
  client/src/components/UserActivityItem/index.tsx
  client/src/components/UserActivityItem/styles.module.scss
  client/src/components/common/TagsInput/index.tsx
  client/src/containers/Filters/logic/helpers.ts
  client/src/containers/ProfilePage/index.tsx
  client/src/containers/ProfilePage/logiс/actionTypes.ts
  client/src/containers/ProfilePage/logiс/actions.ts
  client/src/containers/ProfilePage/logiс/reducer.ts
  client/src/containers/ProfilePage/logiс/saga.ts
  client/src/containers/ProfilePage/logiс/state.ts
  client/src/containers/ProfilePage/styles.module.scss
  client/src/containers/Routing/index.tsx
  client/src/helpers/callApi.helper.ts
  client/src/redux/rootReducer.ts
  client/src/redux/rootSaga.ts
  client/src/services/auth.service.ts
  client/src/services/user.service.ts
  client/src/styles/mixins.scss
  client/src/styles/variables.scss
  client/src/typings/rootState.ts
  client/src/typings/webapi.d.ts
  server/config/passport.config.ts
  server/src/controllers/projects.controllers.ts
  server/src/controllers/user.controllers.ts
  server/src/entity/Board.ts
  server/src/entity/Filter.ts
  server/src/entity/FilterPart.ts
  server/src/entity/TeamsPeople.ts
  server/src/entity/UserProfile.ts
  server/src/models/User.ts
  server/src/repositories/user.repository.ts
  server/src/seeders/1596645895543-User.ts
  server/src/seeders/1596645901833-Board.ts
Labels: enhancement, feature

#49 Feature: localization
  client/package-lock.json
  client/package.json
  client/src/components/DashboardsMenu/index.tsx
  client/src/components/FilterItem/index.tsx
  client/src/components/FiltersMenu/index.tsx
  client/src/components/LanguageSelect/index.tsx
  client/src/components/ProjectsMenu/index.tsx
  client/src/components/TeamDevsCard/index.tsx
  client/src/components/TeamLinks/index.tsx
  client/src/components/TeamNotification/index.tsx
  client/src/components/TeamWorkedProjects/index.tsx
  client/src/components/TeamsMembersCard/index.tsx
  client/src/components/common/PasswordInput/index.tsx
  client/src/components/common/Spinner/index.tsx
  client/src/components/common/TagsInput/index.tsx
  client/src/config/i18n.config.ts
  client/src/constants/LocalStorageKeys.ts
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/CreateProjectModal/index.tsx
  client/src/containers/Filters/index.tsx
  client/src/containers/Header/index.tsx
  client/src/containers/Header/styles.module.scss
  client/src/containers/LoginPage/index.tsx
  client/src/containers/Projects/index.tsx
  client/src/containers/SignUpForm/index.tsx
  client/src/containers/UpdateIssueModal/index.tsx
  client/src/helpers/setLng.helper.ts
  client/src/index.tsx
  client/src/pages/IssuePage/index.tsx
  client/src/pages/IssuePage/styles.module.scss
  client/src/pages/SignUp/index.tsx
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
Labels: enhancement, feature, refactoring

#53 Fix language format bug. Fix user repository error bug
  client/src/components/UserActivityItem/index.tsx
  client/src/config/i18n.config.ts
  client/src/containers/ProfilePage/index.tsx
  server/src/repositories/user.repository.ts
Labels: enhancement, fix

#55 Feature/project settings
  client/src/components/ProjectSidebar/index.tsx
  client/src/components/ProjectSidebar/styles.module.scss
  client/src/containers/CreateProjectModal/config/templatesInformation.ts
  client/src/containers/ProjectSettings/index.tsx
Labels: enhancement

#56 Fix different language formats
  client/src/components/LanguageSelect/index.tsx
  client/src/config/i18n.config.ts
  client/src/helpers/getLanguage.helper.ts
Labels: enhancement, fix

#58 Fix/redirect to projects after login
  client/src/components/PublicRoute/index.tsx
  client/src/containers/LoginPage/index.tsx
Labels: fix, refactoring

#57 Fix eslint errors
  client/.eslintrc.json
  server/index.ts
  server/scripts/update_webapi.ts
  server/src/repositories/user.repository.ts
Labels: enhancement, fix, refactoring

#59 Add seeders for Filters and Projects
  server/src/seeders/1597048908491-Project.ts
  server/src/seeders/1597050485179-FilterDef.ts
  server/src/seeders/1597050608478-Filter.ts
Labels: enhancement

#60 Fix image size сss-bug
  client/src/components/Avatar/styles.module.scss
Labels: fix

#61 Fix/projects redirect
  client/src/containers/CreateProjectModal/index.tsx
  client/src/containers/Routing/index.tsx
  client/src/pages/ProjectSettings/index.tsx
Labels: fix

#62 Fix/header layout on pages
  client/src/components/FiltersMenu/index.tsx
  client/src/components/ProjectsMenu/index.tsx
  client/src/containers/DefaultPageWrapper/index.tsx
  client/src/containers/DefaultPageWrapper/styles.module.scss
  client/src/containers/Header/index.tsx
  client/src/containers/Header/styles.module.scss
  client/src/containers/ProfilePage/index.tsx
  client/src/containers/Routing/index.tsx
Labels: bug, fix

#63 Solve lint errors
  client/src/components/ProjectSidebar/index.tsx
  client/src/containers/CreateProjectModal/index.tsx
  client/src/containers/LoginPage/index.tsx
Labels: fix

#65 Add issue card
  client/package-lock.json
  client/package.json
  client/src/components/IssueCard/index.tsx
  client/src/components/IssueCard/styles.module.scss
  client/src/components/ProjectSidebar/index.tsx
  client/src/containers/ProfilePage/index.tsx
  client/src/containers/Routing/index.tsx
  client/src/services/issue.service.ts
Labels: enhancement, feature

#66 Fix/breadcrambs console error
  client/src/components/common/Breadcrumbs/index.tsx
  client/src/containers/ProjectSettings/config/breadcrumbs.ts
Labels: fix

#32 Add CRUD for Sprints
  client/src/containers/CreateIssueModal/body.tsx
  client/src/typings/webapi.d.ts
  server/src/controllers/sprint.controllers.ts
  server/src/entity/Board.ts
  server/src/entity/Issue.ts
  server/src/entity/Projects.ts
  server/src/entity/Sprint.ts
  server/src/models/Issue.ts
  server/src/models/Result.ts
  server/src/repositories/projects.repository.ts
  server/src/repositories/sprint.repository.ts
  server/src/routes/index.ts
  server/src/routes/sprint.routes.ts
  server/src/seeders/1597046103388-Sprint.ts
  server/src/seeders/1597048908491-Project.ts
Labels: feature

#70 Fix setting to default locale
  client/src/components/LanguageSelect/index.tsx
Labels: enhancement, fix

#69 Add kanban board
  .DS_Store
  client/.DS_Store
  client/src/.DS_Store
  client/src/components/IssueCard/index.tsx
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/Board/Kanban/styles.module.scss
  client/src/containers/Board/index.tsx
  client/src/containers/BoardColumn/index.tsx
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/CreateIssueModal/index.tsx
  client/src/containers/DefaultPageWrapper/index.tsx
  client/src/containers/Header/index.tsx
  client/src/containers/Header/styles.module.scss
  client/src/containers/Routing/index.tsx
  client/src/containers/UpdateIssueModal/index.tsx
  client/src/helpers/extractId.helper.ts
  client/src/pages/BoardPage/index.tsx
  client/src/pages/CreateIssue/index.tsx
  client/src/pages/IssuePage/index.tsx
  client/src/pages/IssuePage/logic/actionTypes.ts
  client/src/pages/IssuePage/logic/actions.ts
  client/src/pages/IssuePage/logic/initialState.ts
  client/src/pages/IssuePage/logic/reducer.ts
  client/src/pages/IssuePage/logic/saga.ts
  client/src/pages/IssuePage/logic/types.ts
  client/src/redux/rootReducer.ts
  client/src/redux/rootSaga.ts
  client/src/services/board.service.ts
  client/src/services/issue.service.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  client/src/typings/rootState.ts
  client/src/typings/webapi.d.ts
  server/src/controllers/issue.controllers.ts
  server/src/entity/BoardColumn.ts
  server/src/entity/Issue.ts
  server/src/models/Issue.ts
  server/src/models/Result.ts
  server/src/repositories/board.repository.ts
  server/src/repositories/issue.repository.ts
  server/src/routes/boardColumn.routes.ts
  server/src/routes/issue.routes.ts
Labels: enhancement, feature

#81 Feature/project settings
  client/src/containers/ProjectSettings/config/breadcrumbs.ts
  client/src/containers/ProjectSettings/form.tsx
  client/src/containers/ProjectSettings/index.tsx
  client/src/containers/ProjectSettings/logic/actionTypes.ts
  client/src/containers/ProjectSettings/logic/actions.ts
  client/src/containers/ProjectSettings/logic/reducer.ts
  client/src/containers/ProjectSettings/logic/saga.ts
  client/src/containers/ProjectSettings/logic/state.ts
  client/src/containers/ProjectSettings/styles.module.scss
  client/src/redux/rootReducer.ts
  client/src/redux/rootSaga.ts
  client/src/services/projects.service.ts
  client/src/typings/rootState.ts
  server/src/entity/Projects.ts
  server/src/entity/UserProfile.ts
Labels: enhancement

#84 Add users relations to projects
  server/src/entity/Projects.ts
  server/src/entity/UserProfile.ts
Labels: enhancement

#82 Feature: project issues page
  client/src/components/IssueCard/index.tsx
  client/src/components/ProjectIssuesColumn/index.tsx
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/BoardColumn/index.tsx
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/CreateIssueModal/index.tsx
  client/src/containers/Header/index.tsx
  client/src/containers/IssuePageContent/index.tsx
  client/src/containers/ProjectIssuesPage/index.tsx
  client/src/containers/ProjectSettings/logic/saga.ts
  client/src/containers/Routing/index.tsx
  client/src/containers/UpdateIssueModal/index.tsx
  client/src/pages/IssuePage/index.tsx
  client/src/pages/ProjectIssues/index.tsx
  client/src/services/projects.service.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  server/src/controllers/issue.controllers.ts
  server/src/repositories/issue.repository.ts
  server/src/routes/projects.routes.ts
Labels: enhancement, feature

#88 Little localization and data types fixes
  client/src/components/ProjectIssuesColumn/index.tsx
  client/src/containers/BoardColumn/index.tsx
  client/src/containers/ProjectIssuesPage/index.tsx
  client/src/services/projects.service.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
Labels: fix

#89 Fix: tags input style
  client/src/components/common/TagsInput/index.tsx
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/UpdateIssueModal/index.tsx
Labels: enhancement, fix

#91 Header redesign
  client/src/components/AccountManager/index.tsx
  client/src/containers/Header/index.tsx
  client/src/containers/Header/styles.module.scss
  client/src/containers/ProfilePage/index.tsx
  client/src/styles/index.scss
  client/src/styles/variables.scss
Labels: enhancement, fix, redesign, refactoring

#92 Redesign KanbanBoard
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/Board/Kanban/styles.module.scss
  client/src/containers/BoardColumn/index.tsx
  client/src/containers/BoardColumn/styles.module.scss
  server/src/controllers/issue.controllers.ts
  server/src/routes/issue.routes.ts
Labels: enhancement, fix, redesign, refactoring

#75 Feature/email check on log in
  client/src/containers/LoginPage/index.tsx
  client/src/containers/LoginPage/logic/actionTypes.ts
  client/src/containers/LoginPage/logic/actions.ts
  client/src/containers/LoginPage/logic/reducer.ts
  client/src/containers/LoginPage/logic/saga.ts
  client/src/containers/LoginPage/logic/state.ts
  client/src/services/auth.service.ts
  client/src/typings/webapi.d.ts
  server/config/jwt.config.ts
  server/config/passport.config.ts
  server/src/controllers/auth.controllers.ts
  server/src/middleware/checkEmail.middleware..ts
  server/src/models/User.ts
  server/src/routes/auth.routes.ts
  server/src/seeders/1596645895543-User.ts
Labels: enhancement

#93 Add 404 page
  client/src/assets/images/404.png
  client/src/containers/Routing/index.tsx
  client/src/pages/404/index.tsx
  client/src/pages/404/styles.module.scss
Labels: enhancement

#96 Feature: create issue modal improvements
  client/src/components/common/TagsInput/index.tsx
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/DefaultPageWrapper/index.tsx
  client/src/containers/Projects/index.tsx
  server/src/repositories/user.repository.ts
  server/src/seeders/1596718071573-Priority.ts
  server/src/seeders/1597048908491-Project.ts
Labels: enhancement, feature, fix, refactoring

#102 Feature: issue creator
  client/package-lock.json
  client/package.json
  client/src/components/IssueItem/index.tsx
  client/src/containers/AdvancedSearch/index.tsx
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/CreateIssueModal/logic/initalState.ts
  client/src/containers/IssuePageContent/index.tsx
  client/src/pages/IssuePage/logic/types.ts
  client/src/typings/webapi.d.ts
  server/src/entity/Issue.ts
  server/src/models/Issue.ts
  server/src/models/Result.ts
  server/src/repositories/issue.repository.ts
  server/src/seeders/1596719363245-IssueType.ts
Labels: enhancement, feature, fix, refactoring

#98 Update entities relations
  client/package-lock.json
  client/package.json
  client/src/typings/webapi.d.ts
  server/src/controllers/teams.controllers.ts
  server/src/entity/Board.ts
  server/src/entity/BoardColumn.ts
  server/src/entity/Filter.ts
  server/src/entity/FilterDefinition.ts
  server/src/entity/FilterPart.ts
  server/src/entity/Issue.ts
  server/src/entity/IssueType.ts
  server/src/entity/Priority.ts
  server/src/entity/Projects.ts
  server/src/entity/Sprint.ts
  server/src/entity/Team.ts
  server/src/entity/Teams.ts
  server/src/entity/TeamsPeople.ts
  server/src/entity/UserProfile.ts
  server/src/repositories/teams.repository.ts
  server/src/seeders/1606645895543-Teams.ts
Labels: refactoring

#103 Refactor: Add types, separate components, filter definition auto increment
  client/src/commonLogic/users/saga.ts
  client/src/components/FilterPart/DropdownComponents/CheckboxSearch.tsx
  client/src/components/FilterPart/DropdownComponents/TextSearch.tsx
  client/src/components/FilterPart/FilterComponents/AssigneeFilter.tsx
  client/src/components/FilterPart/FilterComponents/CommentFilter.tsx
  client/src/components/FilterPart/FilterComponents/CreatorFilter.tsx
  client/src/components/FilterPart/FilterComponents/DescriptionFilter.tsx
  client/src/components/FilterPart/FilterComponents/IssueStatusFilter.tsx
  client/src/components/FilterPart/FilterComponents/IssueTypeFilter.tsx
  client/src/components/FilterPart/FilterComponents/PriorityFilter.tsx
  client/src/components/FilterPart/FilterComponents/ProjectsFilter.tsx
  client/src/components/FilterPart/FilterComponents/SummaryFilter.tsx
  client/src/components/FilterPart/FilterComponents/helpers.ts
  client/src/components/FilterPart/FilterComponents/index.tsx
  client/src/components/FilterPart/FilterComponents/types.ts
  client/src/components/FilterPart/types.ts
  client/src/components/IssueItem/index.tsx
  client/src/components/MoreFilters/index.tsx
  client/src/constants/FilterDef.ts
  client/src/containers/AdvancedSearch/index.tsx
  client/src/typings/webapi.d.ts
  server/src/entity/FilterDefinition.ts
  server/src/seeders/1597050485179-FilterDef.ts
Labels: fix, refactoring

#101 Feature/team page
  client/package-lock.json
  client/package.json
  client/src/assets/images/team-build.svg
  client/src/assets/images/team-page-links.jpg
  client/src/assets/images/team-page-links.svg
  client/src/assets/images/team-page-works.jpg
  client/src/assets/images/team-page-works.svg
  client/src/components/CreateTeamModal/index.tsx
  client/src/components/CreateTeamModal/styles.module.scss
  client/src/components/TeamAddPeopleModal/aditionalModal.tsx
  client/src/components/TeamAddPeopleModal/index.tsx
  client/src/components/TeamAddPeopleModal/styles.module.scss
  client/src/components/TeamDevsCard/index.tsx
  client/src/components/TeamLinks/createLink.tsx
  client/src/components/TeamLinks/deleteLink.tsx
  client/src/components/TeamLinks/index.tsx
  client/src/components/TeamLinks/linkCard.tsx
  client/src/components/TeamLinks/styles.module.scss
  client/src/components/TeamNotification/index.tsx
  client/src/components/TeamWorkedProjects/index.tsx
  client/src/components/TeamsMembersCard/helper.ts
  client/src/components/TeamsMembersCard/index.tsx
  client/src/components/TeamsMembersCard/styles.module.scss
  client/src/components/common/ModalViewProfile/index.tsx
  client/src/components/common/ModalViewProfile/styles.module.scss
  client/src/containers/Header/styles.module.scss
  client/src/containers/Routing/index.tsx
  client/src/containers/TeamPage/index.tsx
  client/src/containers/TeamPage/logic/actionTypes.ts
  client/src/containers/TeamPage/logic/actions.ts
  client/src/containers/TeamPage/logic/reducer.ts
  client/src/containers/TeamPage/logic/saga.ts
  client/src/containers/TeamPage/logic/state.ts
  client/src/containers/TeamPage/styles.module.scss
  client/src/pages/Team/index.tsx
  client/src/redux/rootReducer.ts
  client/src/redux/rootSaga.ts
  client/src/services/team.service.ts
  client/src/typings/rootState.ts
  client/src/typings/webapi.d.ts
  server/src/controllers/issueType.controllers.ts
  server/src/controllers/teams.controllers.ts
  server/src/entity/Team.ts
  server/src/entity/Teams.ts
  server/src/entity/UserProfile.ts
  server/src/helpers/team.parser.ts
  server/src/migration/1597155507178-Teams.ts
  server/src/models/Team.ts
  server/src/models/User.ts
  server/src/repositories/teams.repository.ts
  server/src/routes/teams.routes.ts
  server/src/seeders/1596645895543-User.ts
  server/src/seeders/1606645895543-Teams.ts
  server/src/seeds/teams.seed.ts
  server/src/seeds/users.seed.ts
Labels: feature

#104 Add issue assignee
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/CreateIssueModal/logic/context.tsx
  client/src/containers/DefaultPageWrapper/index.tsx
  client/src/containers/IssuePageContent/index.tsx
  client/src/containers/UpdateIssueModal/index.tsx
  client/src/helpers/getUsername.helper.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  client/src/typings/webapi.d.ts
  server/src/entity/UserProfile.ts
  server/src/repositories/issue.repository.ts
Labels: enhancement, feature

#87 Validate email on login and signup
  client/src/containers/LoginPage/index.tsx
  client/src/containers/SignUpForm/index.tsx
  client/src/helpers/normalizeEmail.helper.ts
  server/config/passport.config.ts
  server/package-lock.json
  server/package.json
  server/src/constants/auth.constants.ts
  server/src/controllers/auth.controllers.ts
  server/src/controllers/issue.controllers.ts
  server/src/controllers/user.controllers.ts
  server/src/entity/Board.ts
  server/src/entity/BoardColumn.ts
  server/src/entity/Filter.ts
  server/src/entity/FilterDefinition.ts
  server/src/entity/FilterPart.ts
  server/src/entity/Issue.ts
  server/src/entity/IssueType.ts
  server/src/entity/Priority.ts
  server/src/entity/Projects.ts
  server/src/entity/Sprint.ts
  server/src/entity/Team.ts
  server/src/entity/UserProfile.ts
  server/src/middleware/checkEmail.middleware..ts
  server/src/routes/auth.routes.ts
  server/validators/validateUserProfile.validator.ts
Labels: enhancement, feature

#105 Add issue comment crud
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/TeamPage/index.tsx
  client/src/typings/webapi.d.ts
  server/src/controllers/issue.controllers.ts
  server/src/controllers/issueComment.controllers.ts
  server/src/entity/IssueComment.ts
  server/src/models/Issue.ts
  server/src/repositories/issueComment.repository.ts
  server/src/routes/issue.routes.ts
  server/src/routes/issueComment.routes.ts
  server/src/seeders/1596645895543-User.ts
Labels: enhancement, feature

#106 Fix eslint error
  server/src/controllers/issueComment.controllers.ts
Labels: fix

#100 Backend feature/advanced search
  server/src/controllers/issue.controllers.ts
  server/src/repositories/issue.repository.ts
Labels: enhancement, feature

#111 Backend fix conflict
  server/src/repositories/issue.repository.ts
Labels: bug, fix

#112 Fix CORS issue
  server/index.ts
Labels: fix

#114 Drop DB on npm run prod
  server/package.json
Labels: fix

#115 Add * to cors origin
  server/index.ts
Labels: fix

#116 Fix/enable cors for aws staging v2
  server/index.ts
Labels: fix

#113 Fix header
  client/src/containers/Header/index.tsx
  client/src/containers/Header/styles.module.scss
  client/src/styles/index.scss
Labels: enhancement, feature, fix, redesign, refactoring

#117 Feature/Load filtered issues on filter selection
  client/src/components/FilterPart/DropdownComponents/CheckboxSearch.tsx
  client/src/components/FilterPart/DropdownComponents/TextSearch.tsx
  client/src/components/FilterPart/FilterComponents/AssignedFilter.tsx
  client/src/components/FilterPart/FilterComponents/CommentFilter.tsx
  client/src/components/FilterPart/FilterComponents/CreatorFilter.tsx
  client/src/components/FilterPart/FilterComponents/DescriptionFilter.tsx
  client/src/components/FilterPart/FilterComponents/ProjectsFilter.tsx
  client/src/components/FilterPart/FilterComponents/SummaryFilter.tsx
  client/src/components/FilterPart/FilterComponents/helpers.ts
  client/src/components/FilterPart/FilterComponents/index.tsx
  client/src/components/FilterPart/helper.tsx
  client/src/components/IssueItem/index.tsx
  client/src/components/SearchTitle/index.tsx
  client/src/components/SearchTitle/styles.module.scss
  client/src/containers/AdvancedSearch/AdvancedFilters/index.tsx
  client/src/containers/AdvancedSearch/AdvancedFilters/styles.module.scss
  client/src/containers/AdvancedSearch/IssueTable/index.tsx
  client/src/containers/AdvancedSearch/index.tsx
  client/src/containers/AdvancedSearch/logic/actionTypes.ts
  client/src/containers/AdvancedSearch/logic/actions.ts
  client/src/containers/AdvancedSearch/logic/helpers.ts
  client/src/containers/AdvancedSearch/logic/reducer.ts
  client/src/containers/AdvancedSearch/logic/saga.ts
  client/src/containers/AdvancedSearch/logic/state.ts
  client/src/containers/AdvancedSearch/styles.module.scss
  client/src/services/issue.service.ts
  server/src/controllers/filterPart.controllers.ts
  server/src/controllers/issue.controllers.ts
  server/src/helpers/issue.helper.ts
  server/src/repositories/issue.repository.ts
  server/src/routes/filterPart.routes.ts
  server/src/routes/issue.routes.ts
  server/src/seeders/1597050485179-FilterDef.ts
  server/src/seeders/1597334747593-Issue.ts
Labels: enhancement, refactoring

#72 Feature/profile manager
  client/package-lock.json
  client/package.json
  client/src/components/AccountManager/index.tsx
  client/src/components/ContentInput/index.tsx
  client/src/components/ContentInput/styles.module.scss
  client/src/components/EmailManager/index.tsx
  client/src/components/EmailManager/styles.module.scss
  client/src/components/ManagerAsideBlock/index.tsx
  client/src/components/ManagerAsideBlock/styles.module.scss
  client/src/components/PasswordCheck/index.tsx
  client/src/components/PasswordCheck/styles.module.scss
  client/src/components/ProfileAboutBlock/index.tsx
  client/src/components/ProfileAboutItem/index.tsx
  client/src/components/ProfileAboutItem/styles.module.scss
  client/src/components/ProfileAside/index.tsx
  client/src/components/ProfileContactBlock/index.tsx
  client/src/components/ProfileManager/index.tsx
  client/src/components/ProfileManager/styles.module.scss
  client/src/components/ProfileManagerSection/index.tsx
  client/src/components/ProfilePicture/index.tsx
  client/src/components/ProfilePicture/styles.module.scss
  client/src/components/ProfileSection/index.tsx
  client/src/components/ProfileTeamBlock/index.tsx
  client/src/components/SecurityManager/index.tsx
  client/src/components/SecurityManager/styles.module.scss
  client/src/components/SubmitedInput/index.tsx
  client/src/components/SubmitedInput/styles.module.scss
  client/src/containers/Header/styles.module.scss
  client/src/containers/LoginPage/logic/state.ts
  client/src/containers/LoginPage/styles.module.scss
  client/src/containers/ProfilePage/index.tsx
  client/src/containers/ProfilePage/logiс/actionTypes.ts
  client/src/containers/ProfilePage/logiс/actions.ts
  client/src/containers/ProfilePage/logiс/reducer.ts
  client/src/containers/ProfilePage/logiс/saga.ts
  client/src/containers/ProfilePage/logiс/state.ts
  client/src/containers/Routing/index.tsx
  client/src/containers/SignUpForm/styles.module.scss
  client/src/helpers/callApi.helper.ts
  client/src/pages/Profile/index.tsx
  client/src/services/user.service.ts
  client/src/styles/mixins.scss
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  server/.env.example
  server/config/aws.config.ts
  server/libs/aws.ts
  server/package-lock.json
  server/package.json
  server/src/controllers/user.controllers.ts
  server/src/entity/Filter.ts
  server/src/entity/UserProfile.ts
  server/src/helpers/image.helper.ts
  server/src/middleware/imageMiddleware.ts
  server/src/models/User.ts
  server/src/repositories/user.repository.ts
  server/src/routes/user.routes.ts
Labels: enhancement, feature

#118 Fix ProjectIssuesPage styling
  client/src/components/BoardModalFinal/index.tsx
  client/src/components/IssueCard/index.tsx
  client/src/components/ProjectIssuesColumn/index.tsx
  client/src/containers/ProjectIssuesPage/index.tsx
  client/src/containers/ProjectIssuesPage/styles.module.scss
Labels: enhancement, feature, fix, redesign, refactoring

#119 Feature: issue comments and issue page styling
  client/package-lock.json
  client/package.json
  client/src/components/BoardsMenu/index.tsx
  client/src/components/IssueComment/index.tsx
  client/src/components/IssueComment/styles.module.scss
  client/src/components/IssueCommentForm/index.tsx
  client/src/components/IssueCommentForm/logic/actionTypes.ts
  client/src/components/IssueCommentForm/logic/actions.ts
  client/src/components/IssueCommentForm/logic/saga.ts
  client/src/components/IssueCommentForm/styles.module.scss
  client/src/components/ProfilePicture/index.tsx
  client/src/containers/Header/index.tsx
  client/src/containers/IssuePageContent/index.tsx
  client/src/containers/IssuePageContent/styles.module.scss
  client/src/containers/ProjectIssuesPage/index.tsx
  client/src/helpers/getInitials.helper.ts
  client/src/pages/IssuePage/index.tsx
  client/src/redux/rootSaga.ts
  client/src/services/issue.service.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  client/src/typings/webapi.d.ts
  server/src/models/Result.ts
  server/src/repositories/issueComment.repository.ts
Labels: enhancement, feature, redesign

#121 Add sticky to create issue modal
  client/src/containers/CreateIssueModal/body.tsx
Labels: enhancement, fix, refactoring

#128 Feature/save advanced search (Save Filter)
  client/src/containers/SaveFilterModal/index.tsx
  client/src/containers/SaveFilterModal/logic/actionTypes.ts
  client/src/containers/SaveFilterModal/logic/saga.ts
  client/src/containers/SaveFilterModal/styles.module.scss
  server/src/entity/Filter.ts
  server/src/entity/FilterPart.ts
  server/src/repositories/filter.repository.ts
  server/src/repositories/filterPart.repository.ts
Labels: enhancement

#126 Feature/profile design
  client/public/index.html
  client/src/components/AccountManager/index.tsx
  client/src/components/AccountManager/styles.module.scss
  client/src/components/ContentInput/styles.module.scss
  client/src/components/EmailManager/index.tsx
  client/src/components/EmailManager/styles.module.scss
  client/src/components/LanguageSelect/index.tsx
  client/src/components/LanguageSelect/styles.module.scss
  client/src/components/ManagerAsideBlock/styles.module.scss
  client/src/components/ProfileAboutBlock/index.tsx
  client/src/components/ProfileAboutBlock/styles.module.scss
  client/src/components/ProfileAboutItem/index.tsx
  client/src/components/ProfileAboutItem/styles.module.scss
  client/src/components/ProfileActivityBlock/index.tsx
  client/src/components/ProfileActivityBlock/styles.module.scss
  client/src/components/ProfileAside/index.tsx
  client/src/components/ProfileAside/styles.module.scss
  client/src/components/ProfileContactBlock/index.tsx
  client/src/components/ProfileContactBlock/styles.module.scss
  client/src/components/ProfileHeader/index.tsx
  client/src/components/ProfileHeader/styles.module.scss
  client/src/components/ProfileManager/index.tsx
  client/src/components/ProfileManager/styles.module.scss
  client/src/components/ProfilePicture/styles.module.scss
  client/src/components/ProfileSection/index.tsx
  client/src/components/ProfileSection/styles.module.scss
  client/src/components/ProfileTeamBlock/index.tsx
  client/src/components/ProfileTeamBlock/styles.module.scss
  client/src/components/SecurityManager/index.tsx
  client/src/components/SecurityManager/styles.module.scss
  client/src/components/SubmitedInput/styles.module.scss
  client/src/components/UserActivityItem/index.tsx
  client/src/components/UserActivityItem/styles.module.scss
  client/src/config/i18n.config.ts
  client/src/containers/ProfilePage/index.tsx
  client/src/containers/ProfilePage/styles.module.scss
  client/src/icons/profile/Union.svg
  client/src/icons/profile/clock.svg
  client/src/icons/profile/geo.svg
  client/src/icons/profile/mail.svg
  client/src/icons/profile/projectIcon.svg
  client/src/icons/profile/reorder.svg
  client/src/icons/profile/teamIcon.svg
  client/src/icons/profile/toolbox.svg
  client/src/styles/index.scss
  client/src/styles/mixins.scss
  client/src/styles/variables.scss
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  server/.env.example
Labels: enhancement, feature

#132 add fixes to classes
  client/src/components/AccountManager/index.tsx
  client/src/components/AccountManager/styles.module.scss
  client/src/components/ContentInput/index.tsx
  client/src/components/ContentInput/styles.module.scss
  client/src/components/EmailManager/index.tsx
  client/src/components/EmailManager/styles.module.scss
  client/src/components/ManagerAsideBlock/styles.module.scss
  client/src/components/PasswordCheck/index.tsx
  client/src/components/PasswordCheck/styles.module.scss
  client/src/components/ProfileActivityBlock/index.tsx
  client/src/components/ProfileActivityBlock/styles.module.scss
  client/src/components/ProfileHeader/index.tsx
  client/src/components/ProfileHeader/styles.module.scss
  client/src/components/ProfilePicture/index.tsx
  client/src/components/ProfilePicture/styles.module.scss
  client/src/components/ProfileSection/index.tsx
  client/src/components/ProfileSection/styles.module.scss
  client/src/components/ProfileTeamBlock/index.tsx
  client/src/components/ProfileTeamBlock/styles.module.scss
  client/src/components/SecurityManager/styles.module.scss
  client/src/components/UserActivityItem/index.tsx
  client/src/components/UserActivityItem/styles.module.scss
Labels: fix

#124 Add notifications to team page actions
  client/src/components/TeamDevsCard/index.tsx
  client/src/containers/TeamPage/index.tsx
  client/src/containers/TeamPage/logic/actionTypes.ts
  client/src/containers/TeamPage/logic/actions.ts
  client/src/containers/TeamPage/logic/reducer.ts
  client/src/containers/TeamPage/logic/saga.ts
  client/src/containers/TeamPage/logic/state.ts
  client/src/services/team.service.ts
  client/src/typings/webapi.d.ts
  server/src/controllers/teams.controllers.ts
  server/src/controllers/user.controllers.ts
  server/src/entity/Teams.ts
  server/src/migration/1597155507178-Teams.ts
  server/src/repositories/teams.repository.ts
  server/src/repositories/user.repository.ts
  server/src/seeders/1597311160202-People.ts
  server/src/seeders/1597345244377-Team.ts
  server/src/seeders/1606645895543-Teams.ts
Labels: enhancement, fix

#136 Fix CreateIssueModal styles
  client/src/components/common/TagsInput/index.tsx
  client/src/containers/CreateIssueModal/body.tsx
  client/src/styles/index.scss
Labels: enhancement, fix, redesign, refactoring

#137 Fix UpdateIssueModal
  client/src/containers/UpdateIssueModal/index.tsx
Labels: enhancement, fix, redesign, refactoring

#138 add changes due to demands
  client/src/components/PasswordCheck/index.tsx
  client/src/components/PasswordCheck/styles.module.scss
  client/src/components/ProfileContactBlock/styles.module.scss
  client/src/components/ProfileManager/styles.module.scss
  client/src/components/ProfileTeamBlock/styles.module.scss
  client/src/components/SecurityManager/index.tsx
  client/src/components/SubmitedInput/index.tsx
  client/src/components/SubmitedInput/styles.module.scss
  client/src/components/UserActivityItem/index.tsx
  client/src/containers/WorkPage/styles.module.scss
  client/src/helpers/validation.helper.ts
  client/src/styles/variables.scss
Labels: enhancement, fix

#139 Fix IssuePage styles
  client/src/containers/IssuePageContent/index.tsx
  client/src/containers/IssuePageContent/styles.module.scss
Labels: enhancement, fix, redesign, refactoring

#134 Create Scrum Board view
  client/src/components/Sprint/SprintHeader/index.tsx
  client/src/components/Sprint/SprintHeader/styles.module.scss
  client/src/components/Sprint/SprintIssues/index.tsx
  client/src/components/Sprint/SprintIssues/styles.module.scss
  client/src/components/Sprint/index.tsx
  client/src/components/common/Options/styles.module.scss
  client/src/components/common/SprintModal/index.tsx
  client/src/containers/Board/Scrum/config/breadcrumbs.ts
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/logic/actionTypes.ts
  client/src/containers/Board/Scrum/logic/actions.ts
  client/src/containers/Board/Scrum/logic/reducer.ts
  client/src/containers/Board/Scrum/logic/saga.ts
  client/src/containers/Board/Scrum/logic/state.ts
  client/src/containers/Board/Scrum/style.module.scss
  client/src/containers/Routing/index.tsx
  client/src/helpers/extractUUIDFromArrayOfObjects.helper.ts
  client/src/redux/rootReducer.ts
  client/src/redux/rootSaga.ts
  client/src/services/board.service.ts
  client/src/services/sprint.service.ts
  client/src/typings/rootState.ts
  client/src/typings/webapi.d.ts
  server/src/controllers/board.controller.ts
  server/src/controllers/sprint.controllers.ts
  server/src/entity/Board.ts
  server/src/entity/Issue.ts
  server/src/entity/Sprint.ts
  server/src/repositories/board.repository.ts
  server/src/repositories/sprint.repository.ts
  server/src/routes/board.routes.ts
  server/src/routes/sprint.routes.ts
Labels: enhancement

#142 Feature/load advanced search
  client/src/commonLogic/filterDefs/reducer.ts
  client/src/commonLogic/filterDefs/saga.ts
  client/src/commonLogic/filterDefs/state.ts
  client/src/components/FilterItem/index.tsx
  client/src/components/FilterPart/DropdownComponents/TextSearch.tsx
  client/src/components/FilterPart/DropdownComponents/styles.module.scss
  client/src/components/FilterPart/FilterComponents/IssueStatusFilter.tsx
  client/src/components/FilterPart/FilterComponents/types.ts
  client/src/components/IssueItem/helpers.ts
  client/src/components/IssueItem/index.tsx
  client/src/components/MoreFilters/index.tsx
  client/src/components/SearchTitle/FilterOptions/index.tsx
  client/src/components/SearchTitle/FilterOptions/styles.module.scss
  client/src/components/SearchTitle/index.tsx
  client/src/components/SearchTitle/styles.module.scss
  client/src/containers/AdvancedSearch/AdvancedFilters/index.tsx
  client/src/containers/AdvancedSearch/IssueTable/index.tsx
  client/src/containers/AdvancedSearch/logic/actionTypes.ts
  client/src/containers/AdvancedSearch/logic/actions.ts
  client/src/containers/AdvancedSearch/logic/helpers.ts
  client/src/containers/AdvancedSearch/logic/reducer.ts
  client/src/containers/AdvancedSearch/logic/saga.ts
  client/src/containers/AdvancedSearch/logic/state.ts
  client/src/containers/DefaultPageWrapper/index.tsx
  client/src/containers/Routing/index.tsx
  client/src/containers/SaveFilterModal/index.tsx
  client/src/containers/SaveFilterModal/logic/actionTypes.ts
  client/src/containers/SaveFilterModal/logic/actions.ts
  client/src/containers/SaveFilterModal/logic/reducer.ts
  client/src/containers/SaveFilterModal/logic/saga.ts
  client/src/containers/SaveFilterModal/logic/state.ts
  client/src/containers/TeamPage/logic/actionTypes.ts
  client/src/containers/TeamPage/logic/reducer.ts
  client/src/containers/TeamPage/logic/state.ts
  client/src/pages/IssuePage/logic/actionTypes.ts
  client/src/pages/IssuePage/logic/actions.ts
  client/src/pages/IssuePage/logic/initialState.ts
  client/src/pages/IssuePage/logic/reducer.ts
  client/src/pages/IssuePage/logic/saga.ts
  client/src/pages/IssuePage/logic/types.ts
  client/src/services/filter.service.ts
  client/src/services/issue.service.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  client/src/typings/webapi.d.ts
  server/src/controllers/issueStatus.controllers.ts
  server/src/entity/FilterPart.ts
  server/src/entity/Issue.ts
  server/src/entity/IssueStatus.ts
  server/src/repositories/filter.repository.ts
  server/src/repositories/issue.repository.ts
  server/src/repositories/issueStatus.repository.ts
  server/src/routes/issue.routes.ts
  server/src/routes/issueStatus.routes.ts
  server/src/seeders/1597334747592-IssueStatus.ts
  server/src/seeders/1597334747593-Issue.ts
Labels: enhancement

#146 Fix padding values
  client/src/containers/Projects/styles.module.scss
Labels: fix

#148 Feature/scrum board handle no sprints
  client/src/components/Sprint/SprintHeader/index.tsx
  client/src/components/Sprint/SprintIssues/index.tsx
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/style.module.scss
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  server/src/repositories/board.repository.ts
Labels: enhancement

#107 Feature/projects key generator
  client/src/commonLogic/keyGenerator/data.ts
  client/src/commonLogic/keyGenerator/index.ts
  client/src/containers/CreateProjectModal/index.tsx
  client/src/containers/CreateProjectModal/logic/actionTypes.ts
  client/src/containers/CreateProjectModal/logic/actions.ts
  client/src/containers/CreateProjectModal/logic/reducer.ts
  client/src/containers/CreateProjectModal/logic/saga.ts
  client/src/containers/CreateProjectModal/logic/state.ts
  client/src/services/projects.service.ts
  server/src/controllers/projects.controllers.ts
  server/src/repositories/projects.repository.ts
  server/src/routes/projects.routes.ts
Labels: enhancement

#109 Feature/projects server error handling, validation
  client/src/containers/DefaultPageWrapper/index.tsx
  server/src/constants/projects.constants.ts
  server/src/controllers/projects.controllers.ts
  server/src/entity/Projects.ts
  server/src/entity/UserProfile.ts
  server/src/repositories/projects.repository.ts
  server/validators/validateProjects.validator.ts
Labels: enhancement

#150 Fix adaptivity
  client/src/containers/IssuePageContent/styles.module.scss
Labels: enhancement, fix, redesign

#130 Add mentions in comments
  client/src/components/IssueComment/index.tsx
  client/src/components/IssueCommentForm/index.tsx
  client/src/components/IssueCommentTextInput/index.tsx
  client/src/helpers/getDisplayCommentText.helper.tsx
  client/src/services/user.service.ts
  server/src/controllers/user.controllers.ts
  server/src/entity/Team.ts
  server/src/repositories/user.repository.ts
  server/src/routes/teammates.routes.ts
  server/src/routes/user.routes.ts
Labels: enhancement, feature

#147 Feature/project settings
  client/src/assets/images/projectAvatars/1.svg
  client/src/components/common/Input/CustomInput.tsx
  client/src/containers/CreateProjectModal/index.tsx
  client/src/containers/CreateProjectModal/logic/saga.ts
  client/src/containers/CreateProjectModal/styles.module.scss
  client/src/containers/ProjectSettings/form.tsx
  client/src/containers/ProjectSettings/logic/state.ts
  client/src/containers/ProjectSettings/selectIcon.tsx
  client/src/containers/ProjectSettings/styles.module.scss
  client/src/containers/Projects/config/projectActions.ts
  client/src/containers/Projects/index.tsx
  client/src/typings/webapi.d.ts
  server/src/entity/Projects.ts
Labels: enhancement

#151 Feature/fix and improve dropdown view
  client/src/components/FilterPart/DropdownComponents/CheckboxSearch.tsx
  client/src/components/FilterPart/DropdownComponents/styles.module.scss
  client/src/components/FilterPart/styles.module.scss
  client/src/components/SearchTitle/index.tsx
  client/src/containers/AdvancedSearch/AdvancedFilters/index.tsx
  client/src/containers/AdvancedSearch/logic/actionTypes.ts
  client/src/containers/AdvancedSearch/logic/actions.ts
  server/src/repositories/filter.repository.ts
  server/src/seeders/1597050608478-Filter.ts
Labels: fix, styles

#152 Add link to advanced search in header
  client/src/components/FiltersMenu/index.tsx
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
Labels: enhancement

#145 Hotfix/profile page
  client/src/components/AccountManager/styles.module.scss
  client/src/components/EmailManager/styles.module.scss
  client/src/components/ManagerAsideBlock/index.tsx
  client/src/components/ManagerAsideBlock/styles.module.scss
  client/src/components/ManagerWorkBlock/index.tsx
  client/src/components/ManagerWorkBlock/styles.module.scss
  client/src/components/ManagerWorkSection/index.tsx
  client/src/components/ProfileAboutBlock/styles.module.scss
  client/src/components/ProfileContactBlock/styles.module.scss
  client/src/components/ProfileHeader/index.tsx
  client/src/components/ProfileManager/styles.module.scss
  client/src/components/ProfilePicture/index.tsx
  client/src/components/ProfileSection/index.tsx
  client/src/components/ProfileTeamBlock/styles.module.scss
  client/src/components/ProjectCard/index.tsx
  client/src/components/ProjectCard/styles.module.scss
  client/src/components/SecurityManager/styles.module.scss
  client/src/components/UserActivityItem/index.tsx
  client/src/components/WorkProjectBlock/index.tsx
  client/src/components/WorkProjectBlock/styles.module.scss
  client/src/containers/ProfilePage/index.tsx
  client/src/containers/Routing/index.tsx
  client/src/containers/WorkPage/index.tsx
  client/src/containers/WorkPage/styles.module.scss
  client/src/helpers/validation.helper.ts
  client/src/pages/Work/index.tsx
  client/src/services/user.service.ts
  client/src/styles/index.scss
  client/src/styles/mixins.scss
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  server/package-lock.json
  server/package.json
  server/src/controllers/user.controllers.ts
  server/src/models/User.ts
  server/src/repositories/projects.repository.ts
  server/src/repositories/user.repository.ts
  server/src/routes/user.routes.ts
  server/src/seeders/1596645895543-User.ts
  server/src/seeders/1597700889853-ProjectsPeople.ts
Labels: fix

#153 Fix projects column content
  client/src/containers/Projects/index.tsx
Labels: fix

#140 Header elements align
  client/src/components/BoardsMenu/index.tsx
  client/src/components/ProjectsMenu/index.tsx
  client/src/containers/Boards/index.tsx
  client/src/containers/Header/index.tsx
  client/src/containers/Header/styles.module.scss
  client/src/containers/Routing/index.tsx
  client/src/containers/TeamPage/index.tsx
  client/src/containers/TeamPage/logic/state.ts
  client/src/containers/TeamPage/styles.module.scss
  client/src/styles/index.scss
  client/src/styles/variables.scss
Labels: styles

#135 Add users, team owner, projects to team page
  client/src/components/TeamLinks/styles.module.scss
  client/src/components/TeamNotification/index.tsx
  client/src/components/TeamWorkedProjects/index.tsx
  client/src/components/TeamWorkedProjects/styles.module.scss
  client/src/components/TeamsMembersCard/index.tsx
  client/src/components/common/ModalViewProfile/index.tsx
  client/src/containers/TeamPage/index.tsx
  client/src/containers/TeamPage/logic/actionTypes.ts
  client/src/containers/TeamPage/logic/actions.ts
  client/src/containers/TeamPage/logic/reducer.ts
  client/src/containers/TeamPage/logic/saga.ts
  client/src/containers/TeamPage/logic/state.ts
  client/src/containers/TeamPage/styles.module.scss
  client/src/services/team.service.ts
  client/src/typings/webapi.d.ts
  server/src/controllers/teams.controllers.ts
  server/src/entity/Projects.ts
  server/src/entity/Team.ts
  server/src/models/Team.ts
  server/src/repositories/teams.repository.ts
  server/src/routes/teams.routes.ts
  server/src/seeders/1606645895543-Teams.ts
  server/src/seeds/teams.seed.ts
  server/src/seeds/users.seed.ts
Labels: enhancement, fix

#123 Google authentication on login page
  client/.env.example
  client/package-lock.json
  client/package.json
  client/src/assets/images/icon-google.svg
  client/src/containers/LoginPage/index.tsx
  client/src/containers/LoginPage/logic/actionTypes.ts
  client/src/containers/LoginPage/logic/actions.ts
  client/src/containers/LoginPage/logic/reducer.ts
  client/src/containers/LoginPage/logic/saga.ts
  client/src/containers/LoginPage/logic/state.ts
  client/src/containers/LoginPage/styles.module.scss
  client/src/containers/SignUpForm/index.tsx
  client/src/containers/SignUpForm/styles.module.scss
  client/src/helpers/callApi.helper.ts
  client/src/services/auth.service.ts
  server/config/jwt.config.ts
  server/config/nodeMailer.config.ts
  server/src/controllers/auth.controllers.ts
  server/src/controllers/resetPassword.controller.ts
  server/src/controllers/teams.controllers.ts
  server/src/entity/UserProfile.ts
  server/src/models/Board.ts
  server/src/models/Team.ts
  server/src/models/User.ts
  server/src/repositories/teams.repository.ts
  server/src/routes/auth.routes.ts
  server/src/routes/resetPassword.routes.ts
  server/src/services/email.service.ts
  server/validators/validateUserProfile.validator.ts
Labels: feature, fix

#156 Fix/fix build errors
  client/src/containers/LoginPage/logic/saga.ts
  server/src/seeders/1797584277805-UserInvintation.ts
Labels: bug

#157 Add issue seeders && fix board bud
  client/src/components/BoardsMenu/index.tsx
  server/src/seeders/1596719363245-IssueType.ts
  server/src/seeders/1597334747592-IssueStatus.ts
  server/src/seeders/1597334747593-Issue.ts
  server/src/seeders/1597584277805-UserInvintation.ts
Labels: enhancement, fix

#159 Feature/project settings
  client/src/containers/ProjectSettings/form.tsx
  client/src/containers/ProjectSettings/index.tsx
  client/src/containers/ProjectSettings/logic/saga.ts
Labels: enhancement, fix

#164 Scrum board handle sprint creation
  client/src/components/Sprint/SprintHeader/index.tsx
  client/src/components/Sprint/index.tsx
  client/src/components/common/SprintModal/CreateSprintModal/index.tsx
  client/src/components/common/SprintModal/DeleteSprintModal/index.tsx
  client/src/components/common/SprintModal/EditSprintModal/index.tsx
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/logic/actionTypes.ts
  client/src/containers/Board/Scrum/logic/actions.ts
  client/src/containers/Board/Scrum/logic/reducer.ts
  client/src/containers/Board/Scrum/logic/saga.ts
  client/src/containers/Board/Scrum/logic/state.ts
  client/src/services/sprint.service.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  client/src/typings/webapi.d.ts
  server/src/models/Sprint.ts
  server/src/repositories/sprint.repository.ts
Labels: enhancement

#165 Remove import
  client/src/containers/Board/Scrum/logic/saga.ts
Labels: bug

#166 Make parent element display as span
  client/src/containers/Header/index.tsx
Labels: bug

#167 Fix/project validation rules
  client/src/constants/ValidationMessages.ts
  client/src/containers/CreateProjectModal/index.tsx
  client/src/containers/ProjectSettings/form.tsx
  client/src/helpers/validationRules.ts
Labels: enhancement, fix

#168 Feature: mentioned email
  client/src/containers/TeamPage/index.tsx
  client/src/typings/webapi.d.ts
  server/config/nodeMailer.config.ts
  server/src/controllers/issueComment.controllers.ts
  server/src/helpers/getMentionUsers.helper.ts
  server/src/helpers/parseXML.helper.ts
  server/src/models/Team.ts
  server/src/services/email.service.ts
Labels: enhancement, feature

#170 Fix 'black links' bug. Added assignee and creator links
  client/src/containers/Header/index.tsx
  client/src/containers/Header/styles.module.scss
  client/src/containers/IssuePageContent/index.tsx
Labels: enhancement, feature, redesign

#173 Deleted onBlur, add Save button
  client/.env.example
  client/src/components/TeamDevsCard/index.tsx
  client/src/components/TeamLinks/styles.module.scss
  client/src/components/TeamWorkedProjects/styles.module.scss
  client/src/containers/TeamPage/index.tsx
  client/src/containers/TeamPage/styles.module.scss
  client/src/typings/webapi.d.ts
Labels: enhancement, fix

#171 Feature/scrum board seeders
  client/src/containers/ProjectSettings/form.tsx
  server/src/seeders/1596645901833-Board.ts
  server/src/seeders/1597046103388-Sprint.ts
  server/src/seeders/1597048908491-Project.ts
  server/src/seeders/1597049103388-Sprint.ts
  server/src/seeders/1597334747593-Issue.ts
Labels: refactoring

#169 Fix/breadcrumb on scrum board
  client/src/components/common/SprintModal/CreateSprintModal/index.tsx
  client/src/containers/Board/Scrum/config/breadcrumbs.ts
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/logic/actionTypes.ts
  client/src/containers/Board/Scrum/logic/actions.ts
  client/src/containers/Board/Scrum/logic/reducer.ts
  client/src/containers/Board/Scrum/logic/saga.ts
  client/src/containers/Board/Scrum/logic/state.ts
  client/src/index.tsx
  client/src/services/board.service.ts
  client/src/translations/en.ts
  client/src/typings/runTimeFix.ts
  client/src/typings/webapi.d.ts
  server/scripts/runTImeFixGenerator.ts
  server/scripts/update_webapi.ts
  server/src/models/Result.ts
Labels: bug, fix

#174 Fix eslint errors
  server/src/helpers/getMentionUsers.helper.ts
  server/src/helpers/parseXML.helper.ts
Labels: fix

#177 Fixed ProjectIssuesPage styles
  client/src/components/ProjectIssuesColumn/index.tsx
  client/src/containers/IssuePageContent/index.tsx
  client/src/containers/ProjectIssuesPage/index.tsx
  server/src/repositories/projects.repository.ts
Labels: enhancement, fix, redesign, refactoring, styles

#181 Remove token from local storage if token is invalid
  client/src/containers/LoginPage/logic/saga.ts
  server/config/passport.config.ts
Labels: bug

#182 fixed creation problem
  client/src/components/BoardModalFinal/index.tsx
  client/src/containers/Boards/index.tsx
  client/src/containers/Boards/logic/reducer.ts
  client/src/containers/Boards/logic/saga.ts
  client/src/containers/Boards/logic/state.ts
  client/src/containers/Boards/styles.module.scss
Labels: bug

#184 fixed props problem
  client/src/containers/ResetPassword/index.tsx
Labels: bug

#185 Update model
  server/src/models/Team.ts
Labels: bug, fix

#178 Fix/scrum board error on create sprint
  client/src/components/Sprint/SprintIssues/index.tsx
  client/src/components/Sprint/SprintIssues/styles.module.scss
  client/src/components/common/SprintModal/CreateSprintModal/index.tsx
  client/src/components/common/SprintModal/CreateSprintModal/styles.module.scss
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/logic/actionTypes.ts
  client/src/containers/Board/Scrum/logic/actions.ts
  client/src/containers/Board/Scrum/logic/reducer.ts
  client/src/containers/Board/Scrum/logic/saga.ts
  client/src/helpers/getInitials.helper.ts
  client/src/services/sprint.service.ts
  server/src/repositories/sprint.repository.ts
Labels: fix

#190 Fix bug/display img when no projects found
  client/src/assets/images/search-result.svg
  client/src/containers/Projects/index.tsx
  client/src/containers/Projects/styles.module.scss
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
Labels: bug, fix

#179 Make it possible to search issues
  client/package.json
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/logic/actions.ts
  client/src/containers/Board/Scrum/logic/reducer.ts
  client/src/containers/Board/Scrum/logic/state.ts
  client/src/helpers/getIssuesForSprintId.helper.ts
  client/src/helpers/normalizeText.helper.ts
Labels: enhancement

#188 Fix/scrum board minor fixes
  client/src/components/Sprint/SprintIssues/AssigneeAvatar/index.tsx
  client/src/components/Sprint/SprintIssues/AssigneeAvatar/styles.module.scss
  client/src/components/Sprint/SprintIssues/index.tsx
  client/src/components/Sprint/SprintIssues/styles.module.scss
  client/src/components/common/SprintModal/CreateSprintModal/index.tsx
  client/src/components/common/SprintModal/DeleteSprintModal/index.tsx
  client/src/components/common/SprintModal/EditSprintModal/index.tsx
  client/src/components/common/SprintModal/EditSprintModal/styles.module.scss
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
Labels: refactoring

#193 Remove close button
  client/src/containers/CreateProjectModal/index.tsx
Labels: fix

#192 Add error handler and error notification when getting projects list
  client/src/containers/Projects/logic/saga.ts
Labels: enhancement

#183 Fix/seartch people only by group
  client/src/containers/SearchPeopleAndTeamField/ResultPeople/index.tsx
  client/src/containers/SearchPeopleAndTeamField/ResultPeople/styles.module.scss
  client/src/containers/SearchPeopleAndTeamField/ResultTeams/index.tsx
  client/src/containers/SearchPeopleAndTeamField/ResultTeams/style.module.scss
  client/src/containers/SearchPeopleAndTeamField/index.tsx
  client/src/containers/SearchPeopleAndTeamField/logic/actionTypes.ts
  client/src/containers/SearchPeopleAndTeamField/logic/actions.ts
  client/src/containers/SearchPeopleAndTeamField/logic/reducer.ts
  client/src/containers/SearchPeopleAndTeamField/logic/saga.ts
  client/src/containers/SearchPeopleAndTeamField/logic/state.ts
  client/src/helpers/fillResultsToRender.helper.ts
  client/src/redux/rootReducer.ts
  client/src/redux/rootSaga.ts
  client/src/services/people.service.ts
  client/src/services/team.service.ts
  client/src/translations/en.ts
  client/src/typings/entityModifiedForSearchElement.ts
  client/src/typings/rootState.ts
  server/src/controllers/teammates.controllers.ts
  server/src/controllers/teams.controllers.ts
  server/src/controllers/user.controllers.ts
Labels: bug

#194 Update key generation logic
  client/src/commonLogic/keyGenerator/index.ts
Labels: enhancement, fix

#195 Feature/projects remove prodject
  client/src/assets/images/project/1.svg
  client/src/assets/images/project/10.svg
  client/src/assets/images/project/11.svg
  client/src/assets/images/project/12.svg
  client/src/assets/images/project/13.svg
  client/src/assets/images/project/14.svg
  client/src/assets/images/project/15.svg
  client/src/assets/images/project/16.svg
  client/src/assets/images/project/17.svg
  client/src/assets/images/project/18.svg
  client/src/assets/images/project/19.svg
  client/src/assets/images/project/2.svg
  client/src/assets/images/project/20.svg
  client/src/assets/images/project/21.svg
  client/src/assets/images/project/22.svg
  client/src/assets/images/project/23.svg
  client/src/assets/images/project/24.svg
  client/src/assets/images/project/25.svg
  client/src/assets/images/project/3.svg
  client/src/assets/images/project/4.svg
  client/src/assets/images/project/5.svg
  client/src/assets/images/project/6.svg
  client/src/assets/images/project/7.svg
  client/src/assets/images/project/8.svg
  client/src/assets/images/project/9.svg
  client/src/assets/images/project/index.ts
  client/src/components/ProjectSidebar/index.tsx
  client/src/components/ProjectSidebar/styles.module.scss
  client/src/components/ProjectsCommon/ConfirmedTrash.tsx
  client/src/components/ProjectsCommon/logic/actionTypes.ts
  client/src/components/ProjectsCommon/logic/actions.ts
  client/src/components/ProjectsCommon/logic/reducer.ts
  client/src/components/ProjectsCommon/logic/saga.ts
  client/src/components/ProjectsCommon/logic/state.ts
  client/src/components/common/ConfirmModal/index.tsx
  client/src/containers/CreateProjectModal/index.tsx
  client/src/containers/CreateProjectModal/logic/actionTypes.ts
  client/src/containers/ProjectSettings/form.tsx
  client/src/containers/ProjectSettings/index.tsx
  client/src/containers/ProjectSettings/logic/actionTypes.ts
  client/src/containers/ProjectSettings/logic/actions.ts
  client/src/containers/ProjectSettings/logic/reducer.ts
  client/src/containers/ProjectSettings/logic/saga.ts
  client/src/containers/ProjectSettings/selectIcon.tsx
  client/src/containers/ProjectSettings/styles.module.scss
  client/src/containers/Projects/config/projectActions.ts
  client/src/containers/Projects/index.tsx
  client/src/containers/Projects/logic/reducer.ts
  client/src/redux/rootReducer.ts
  client/src/redux/rootSaga.ts
  client/src/typings/rootState.ts
  server/src/entity/Projects.ts
  server/src/repositories/projects.repository.ts
Labels: enhancement, feature

#191 Update active/inactive toggle logic
  client/src/components/common/SprintModal/CreateSprintModal/index.tsx
  client/src/components/common/SprintModal/DeleteSprintModal/index.tsx
  client/src/components/common/SprintModal/EditSprintModal/index.tsx
Labels: enhancement

#208 Add validate image middleware
  server/config/multer.config.ts
  server/package-lock.json
  server/package.json
  server/src/middleware/imageMiddleware.ts
  server/src/routes/user.routes.ts
Labels: enhancement, fix

#209 Update accept attribute
  client/src/components/ProfilePicture/index.tsx
Labels: enhancement, fix

#204 Feature: issue watchers
  client/src/components/IssuePageInfoColumn/index.tsx
  client/src/components/ProfilePicture/index.tsx
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/IssuePageContent/index.tsx
  client/src/containers/LoginPage/logic/state.ts
  client/src/containers/ProjectSettings/logic/state.ts
  client/src/containers/TeamPage/index.tsx
  client/src/containers/UpdateIssueModal/index.tsx
  client/src/helpers/getInitials.helper.ts
  client/src/helpers/getUsername.helper.ts
  client/src/pages/IssuePage/logic/actionTypes.ts
  client/src/pages/IssuePage/logic/actions.ts
  client/src/pages/IssuePage/logic/saga.ts
  client/src/services/issue.service.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  client/src/typings/webapi.d.ts
  server/src/controllers/issue.controllers.ts
  server/src/entity/Issue.ts
  server/src/entity/UserProfile.ts
  server/src/models/Issue.ts
  server/src/models/Result.ts
  server/src/models/User.ts
  server/src/repositories/issue.repository.ts
  server/src/repositories/teammates.repository.ts
  server/src/routes/issue.routes.ts
Labels: enhancement, feature

#210 Remove production source map generation
  client/.env.production
Labels: enhancement, fix

#213 Change medium priority icon
  client/src/styles/index.scss
  server/src/seeders/1596718071573-Priority.ts
Labels: enhancement, fix, styles

#203 Handle sprint deletion on scrum board
  client/src/components/Backlog/backlog.module.scss
  client/src/components/Backlog/index.tsx
  client/src/components/Sprint/SprintHeader/index.tsx
  client/src/components/Sprint/SprintIssues/index.tsx
  client/src/components/Sprint/index.tsx
  client/src/components/common/SprintModal/DeleteSprintModal/index.tsx
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/logic/actionTypes.ts
  client/src/containers/Board/Scrum/logic/actions.ts
  client/src/containers/Board/Scrum/logic/reducer.ts
  client/src/containers/Board/Scrum/logic/saga.ts
  client/src/containers/Board/Scrum/logic/state.ts
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/CreateIssueModal/index.tsx
  client/src/containers/LoginPage/index.tsx
  client/src/containers/ProjectSettings/logic/state.ts
  client/src/services/issue.service.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  client/src/typings/webapi.d.ts
  server/src/controllers/issue.controllers.ts
  server/src/controllers/resetPassword.controller.ts
  server/src/entity/Board.ts
  server/src/entity/Issue.ts
  server/src/entity/UserProfile.ts
  server/src/middleware/imageMiddleware.ts
  server/src/repositories/issue.repository.ts
  server/src/routes/issue.routes.ts
  server/src/seeders/1597334747593-Issue.ts
Labels: enhancement, feature

#206 Add table data sorting
  client/src/containers/ProjectSettings/logic/state.ts
  client/src/containers/Projects/index.tsx
  client/src/containers/Projects/logic/actionTypes.ts
  client/src/containers/Projects/styles.module.scss
  client/src/containers/Projects/table.tsx
Labels: enhancement, feature

#215 Feature: Project GitHub url
  client/src/components/IssuePageInfoColumn/index.tsx
  client/src/components/common/Input/CustomInput.tsx
  client/src/constants/ValidationMessages.ts
  client/src/constants/ValidationMessages.tsx
  client/src/containers/CreateProjectModal/index.tsx
  client/src/containers/CreateProjectModal/logic/actionTypes.ts
  client/src/helpers/validationRules.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  client/src/typings/webapi.d.ts
  server/src/entity/Projects.ts
  server/src/models/Result.ts
  server/validators/validateProjects.validator.ts
Labels: enhancement, feature, will update

#214 Fix opening create project modal
  client/src/components/BoardsMenu/index.tsx
  client/src/components/ProjectsMenu/index.tsx
  client/src/containers/CreateProjectModal/index.tsx
  client/src/containers/CreateProjectModal/logic/actionTypes.ts
  client/src/containers/CreateProjectModal/logic/actions.ts
  client/src/containers/CreateProjectModal/logic/reducer.ts
  client/src/containers/CreateProjectModal/logic/state.ts
  client/src/containers/Header/index.tsx
  client/src/containers/Projects/index.tsx
Labels: enhancement, fix

#219 Fix/options confirm
  client/src/components/common/ConfirmModal/index.tsx
  client/src/components/common/Options/index.tsx
  client/src/components/common/UserAvatar/index.tsx
  client/src/components/common/UserAvatar/styles.module.scss
  client/src/containers/Header/index.tsx
  client/src/containers/Projects/index.tsx
  client/src/containers/Projects/styles.module.scss
  client/src/containers/Projects/table.tsx
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
Labels: fix

#211 Feature: issue sockets
  client/.env.development
  client/.env.example
  client/.env.production
  client/package-lock.json
  client/package.json
  client/src/components/IssuePageInfoColumn/index.tsx
  client/src/components/ProjectIssuesColumn/index.tsx
  client/src/components/Sprint/SprintIssues/index.tsx
  client/src/components/Sprint/index.tsx
  client/src/config/io.config.ts
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/logic/actionTypes.ts
  client/src/containers/BoardColumn/index.tsx
  client/src/containers/IssuePageContent/index.tsx
  client/src/containers/ProjectIssuesPage/index.tsx
  client/src/containers/ProjectSettings/logic/state.ts
  client/src/containers/UpdateIssueModal/index.tsx
  client/src/hooks/useIO.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  client/src/typings/runTimeFix.ts
  client/src/typings/webapi.d.ts
  server/config/io.config.ts
  server/index.ts
  server/package-lock.json
  server/package.json
  server/src/controllers/issue.controllers.ts
  server/src/customDefinition/cusom.d.ts
  server/src/models/IO.ts
  server/src/models/Result.ts
  server/src/repositories/issue.repository.ts
  server/src/repositories/issueComment.repository.ts
  server/src/repositories/projects.repository.ts
  server/src/socketConnectionHandlers/index.ts
  server/src/socketConnectionHandlers/issue.handler.ts
Labels: enhancement, feature

#216 Add watching issues
  client/package-lock.json
  client/src/components/IssuePageInfoColumn/index.tsx
  client/src/components/NotificationsMenu/index.tsx
  client/src/components/NotificationsMenu/logic/actionTypes.ts
  client/src/components/NotificationsMenu/logic/actions.ts
  client/src/components/NotificationsMenu/logic/reducer.ts
  client/src/components/NotificationsMenu/logic/saga.ts
  client/src/components/NotificationsMenu/logic/state.ts
  client/src/components/common/UserNotification/index.tsx
  client/src/components/common/UserNotification/styles.module.scss
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/DefaultPageWrapper/index.tsx
  client/src/containers/Header/index.tsx
  client/src/containers/Header/styles.module.scss
  client/src/containers/IssuePageContent/index.tsx
  client/src/containers/ProjectIssuesPage/index.tsx
  client/src/redux/rootReducer.ts
  client/src/redux/rootSaga.ts
  client/src/services/notification.service.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  client/src/typings/rootState.ts
  client/src/typings/webapi.d.ts
  server/library-ext.d.ts
  server/src/AI/selectUpdateIssueWatchNotificationMessage.ai.ts
  server/src/controllers/notification.controller.ts
  server/src/entity/Issue.ts
  server/src/entity/IssueStatus.ts
  server/src/entity/IssueType.ts
  server/src/entity/Notification.ts
  server/src/entity/UserProfile.ts
  server/src/helpers/isEqual.helper.ts
  server/src/helpers/isEquivalent.helper.ts
  server/src/helpers/objectsDiff.helper.ts
  server/src/helpers/sentence.helper.ts
  server/src/helpers/templatedReplace.helper.ts
  server/src/models/Issue.ts
  server/src/models/Result.ts
  server/src/models/User.ts
  server/src/repositories/issue.repository.ts
  server/src/repositories/issueComment.repository.ts
  server/src/repositories/notification.repository.ts
  server/src/routes/notification.routes.ts
  server/src/routes/user.routes.ts
  server/typing/Dictionary.ts
Labels: enhancement, feature

#227 Feature: notification sockets
  client/src/components/IssuePageInfoColumn/index.tsx
  client/src/components/NotificationsMenu/index.tsx
  client/src/components/NotificationsMenu/logic/actionTypes.ts
  client/src/components/NotificationsMenu/logic/state.ts
  client/src/components/common/UserNotification/index.tsx
  client/src/config/io.config.ts
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/IssuePageContent/index.tsx
  client/src/hooks/useIO.ts
  client/src/services/notification.service.ts
  client/src/typings/runTimeFix.ts
  client/src/typings/webapi.d.ts
  server/src/entity/Notification.ts
  server/src/models/IO.ts
  server/src/models/Result.ts
  server/src/repositories/notification.repository.ts
  server/src/socketConnectionHandlers/index.ts
  server/src/socketConnectionHandlers/notification.handler.ts
Labels: enhancement, feature

#226 Fix priority sort bug
  server/src/entity/Priority.ts
Labels: fix

#228 Fix eslint errors
  server/config/io.config.ts
  server/index.ts
  server/src/helpers/isEqual.helper.ts
  server/src/helpers/isEquivalent.helper.ts
  server/src/helpers/objectsDiff.helper.ts
  server/src/helpers/sentence.helper.ts
  server/src/helpers/templatedReplace.helper.ts
  server/src/repositories/issue.repository.ts
  server/src/repositories/issueComment.repository.ts
  server/src/routes/notification.routes.ts
  server/src/socketConnectionHandlers/index.ts
Labels: enhancement, fix, refactoring

#229 Feature: notification sockets (2)
  client/src/components/IssuePageInfoColumn/index.tsx
  client/src/components/NotificationsMenu/index.tsx
  client/src/components/NotificationsMenu/logic/actionTypes.ts
  client/src/components/NotificationsMenu/logic/state.ts
  client/src/components/common/UserNotification/index.tsx
  client/src/config/io.config.ts
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/IssuePageContent/index.tsx
  client/src/hooks/useIO.ts
  client/src/services/notification.service.ts
  client/src/typings/runTimeFix.ts
  client/src/typings/webapi.d.ts
  server/src/entity/Notification.ts
  server/src/models/IO.ts
  server/src/models/Result.ts
  server/src/repositories/notification.repository.ts
  server/src/socketConnectionHandlers/notification.handler.ts
Labels: duplicate, enhancement, fix

#235 a few tasks from to do column with high priority
  client/src/components/AdvancedSearch/MoreFilters/index.tsx
  client/src/containers/Filters/index.tsx
  client/src/translations/en.ts
Labels: fix

#230 Feature: push notifications
  client/src/components/NotificationsMenu/index.tsx
  client/src/config/push.config.ts
  client/src/constants/LocalStorageKeys.ts
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/IssuePageContent/index.tsx
  client/src/containers/ProjectIssuesPage/index.tsx
  client/src/index.tsx
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/typings/webapi.d.ts
  server/src/controllers/issue.controllers.ts
  server/src/controllers/issueComment.controllers.ts
  server/src/models/Issue.ts
  server/src/models/Result.ts
  server/src/repositories/issue.repository.ts
  server/src/repositories/issueComment.repository.ts
  server/src/repositories/notification.repository.ts
Labels: enhancement, feature

#220 Feature/validation middleware
  client/src/components/ConfirmPassModal/index.tsx
  client/src/components/EmailManager/index.tsx
  client/src/components/ManagerWorkSection/index.tsx
  client/src/components/PasswordCheck/index.tsx
  client/src/components/ProfileAboutBlock/index.tsx
  client/src/components/ProfileActivityBlock/index.tsx
  client/src/components/ProfileActivityBlock/styles.module.scss
  client/src/components/ProfileAside/index.tsx
  client/src/components/ProfileManager/index.tsx
  client/src/components/ProfileSection/index.tsx
  client/src/components/ProfileTeamBlock/index.tsx
  client/src/components/SecurityManager/index.tsx
  client/src/components/SubmitedInput/index.tsx
  client/src/components/UserActivityItem/index.tsx
  client/src/containers/ProfilePage/index.tsx
  client/src/containers/ResetPassword/index.tsx
  client/src/helpers/validation.helper.ts
  client/src/services/user.service.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  server/package-lock.json
  server/package.json
  server/src/controllers/user.controllers.ts
  server/src/entity/Projects.ts
  server/src/middleware/request.validation.middleware.ts
  server/src/repositories/user.repository.ts
  server/src/requests/Board.ts
  server/src/requests/Filter.ts
  server/src/requests/Issue.ts
  server/src/requests/Project.ts
  server/src/requests/Sprint.ts
  server/src/requests/Team.ts
  server/src/requests/User.ts
  server/src/routes/index.ts
  server/src/routes/user.routes.ts
Labels: enhancement, feature
