Repository BinaryStudioAcademy/bsa-2020-TaskyHusky, pull requests merged in 2020-09, with the labels that each got.

#280 Remove isLoading update on SUCCESS_GET_RECENT_BOARDS
  client/src/containers/Boards/logic/reducer.ts
Labels: bug, fix

#287 Fixed the project modal bug
  client/src/containers/CreateProjectModal/index.tsx
  client/src/containers/CreateProjectModal/logic/reducer.ts
Labels: enhancement, fix

#288 add mixins for btn
  client/src/components/AccountManager/styles.module.scss
  client/src/components/ConfirmPassModal/index.tsx
  client/src/components/DeleteUserModal/index.tsx
  client/src/components/EmailManager/styles.module.scss
  client/src/components/ManagerAsideBlock/styles.module.scss
  client/src/components/ProfileManager/styles.module.scss
  client/src/components/ProfilePicture/styles.module.scss
  client/src/components/SecurityManager/styles.module.scss
  client/src/styles/index.scss
  client/src/styles/mixins.scss
Labels: enhancement, fix

#290 Hotfix/profile styles
  client/src/components/EmailManager/styles.module.scss
  client/src/components/JobTitleSelect/styles.module.scss
  client/src/components/LanguageSelect/styles.module.scss
  client/src/components/SubmitedInput/styles.module.scss
  client/src/styles/mixins.scss
Labels: enhancement, fix

#291 Update issue page styles
  client/src/components/IssuePageInfoColumn/index.tsx
  client/src/containers/IssuePageContent/index.tsx
Labels: enhancement, redesign, refactoring, styles

#292 Update issue modals styles
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/UpdateIssueModal/index.tsx
Labels: enhancement, redesign, refactoring, styles

#293 Update kanban board styles
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/BoardColumn/index.tsx
Labels: enhancement, redesign, refactoring, styles

#289 Added sockets to scrum board
  client/src/components/IssueItem/index.tsx
  client/src/components/Sprint/SprintHeader/index.tsx
  client/src/components/Sprint/SprintIssues/index.tsx
  client/src/components/Sprint/SprintIssues/styles.module.scss
  client/src/components/Sprint/index.tsx
  client/src/components/common/SprintModal/DeleteSprintModal/index.tsx
  client/src/components/common/SprintModal/EditSprintModal/index.tsx
  client/src/containers/AdvancedSearch/logic/actionTypes.ts
  client/src/containers/AdvancedSearch/logic/state.ts
  client/src/containers/Board/Scrum/helpers/logic.helpers.ts
  client/src/containers/Board/Scrum/helpers/reorder.helper.ts
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/logic/actionTypes.ts
  client/src/containers/Board/Scrum/logic/reducer.ts
  client/src/containers/Board/Scrum/logic/saga.ts
  client/src/containers/Board/Scrum/logic/state.ts
  client/src/helpers/getIssuesBySearchText.helper.ts
  client/src/pages/IssuePage/logic/actionTypes.ts
  client/src/pages/IssuePage/logic/saga.ts
  client/src/services/issue.service.ts
  client/src/services/sprint.service.ts
  client/src/typings/webapi.d.ts
  server/src/models/Result.ts
Labels: enhancement, feature

#295 Fix: can't update project
  server/src/entity/Projects.ts
  server/validators/validateProjects.validator.ts
Labels: enhancement, fix, refactoring

#296 Fixed hiding people search input bug
  client/src/containers/ProjectPeople/index.tsx
Labels: enhancement, fix

#297 Fix eslint (3)
  server/src/entity/Projects.ts
  server/validators/validateProjects.validator.ts
Labels: enhancement, fix

#300 Add en localization
  client/src/translations/en.ts
Labels: fix

#302 Update primary button styles
  client/src/styles/mixins.scss
Labels: fix

#298 Feature: create column
  client/src/components/IssueCard/index.tsx
  client/src/components/IssueFileInput/index.tsx
  client/src/components/NotificationsMenu/index.tsx
  client/src/components/common/UserNotification/index.tsx
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/Board/Kanban/styles.module.scss
  client/src/containers/Board/index.tsx
  client/src/containers/BoardColumn/index.tsx
  client/src/containers/BoardColumn/logic/actionTypes.ts
  client/src/containers/BoardColumn/logic/actions.ts
  client/src/containers/BoardColumn/logic/reducer.ts
  client/src/containers/BoardColumn/logic/saga.ts
  client/src/containers/BoardColumn/logic/state.ts
  client/src/containers/BoardColumn/styles.module.scss
  client/src/containers/CreateColumnModal/Body.tsx
  client/src/containers/CreateColumnModal/index.tsx
  client/src/containers/CreateColumnModal/logic/context.tsx
  client/src/containers/CreateColumnModal/logic/initialState.ts
  client/src/containers/Projects/styles.module.scss
  client/src/redux/rootReducer.ts
  client/src/redux/rootSaga.ts
  client/src/services/boardColumn.service.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  client/src/typings/rootState.ts
  client/src/typings/webapi.d.ts
  server/src/entity/BoardColumn.ts
  server/src/models/Board.ts
  server/src/repositories/boardColumn.repository.ts
Labels: enhancement, feature

#303 Add deleting issue
  client/src/components/IssuePageInfoColumn/index.tsx
  client/src/containers/DeleteIssueModal/index.tsx
Labels: enhancement, feature

#294 Fix/projects sorting
  client/src/containers/Projects/styles.module.scss
  client/src/containers/Projects/table.tsx
Labels: fix

#283 Fixed a bug where the user's search bar disappeared
  client/src/containers/ProjectPeople/AddPeopleModal.tsx
  client/src/containers/ProjectPeople/index.tsx
  client/src/containers/ProjectPeople/styles.module.scss
Labels: enhancement, fix

#304 fix styles
  client/src/components/AccountManager/index.tsx
  client/src/components/EmailManager/styles.module.scss
  client/src/components/IssueActivityItem/index.tsx
  client/src/components/IssueActivityItem/styles.module.scss
  client/src/components/ManagerAsideBlock/index.tsx
  client/src/components/ManagerAsideBlock/styles.module.scss
  client/src/components/ProfileAside/index.tsx
  client/src/components/ProfileAside/styles.module.scss
  client/src/components/ProfileManager/index.tsx
  client/src/components/ProfileManagerSection/index.tsx
  client/src/components/ProjectCard/styles.module.scss
  client/src/components/SubmitedInput/styles.module.scss
  client/src/components/UserActivityItem/index.tsx
  client/src/components/WorkIssueCard/index.tsx
  client/src/containers/ProfilePage/index.tsx
  client/src/containers/ProfilePage/logiс/state.ts
  client/src/styles/mixins.scss
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
Labels: enhancement, fix

#305 Added deleting comment
  client/package-lock.json
  client/package.json
  client/src/components/IssueComment/index.tsx
  client/src/components/IssueComment/styles.module.scss
  client/src/components/IssueCommentForm/logic/actionTypes.ts
  client/src/components/IssueCommentForm/logic/actions.ts
  client/src/components/IssueCommentForm/logic/saga.ts
  client/src/services/issue.service.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
Labels: enhancement, feature

#309 Feature/input for elastic search
  client/src/components/AccountManager/index.tsx
  client/src/components/ContainTextInput/index.tsx
  client/src/components/ContainTextInput/styles.module.scss
  client/src/containers/AdvancedSearch/AdvancedFilters/index.tsx
  client/src/containers/AdvancedSearch/index.tsx
  client/src/containers/AdvancedSearch/logic/actionTypes.ts
  client/src/containers/AdvancedSearch/logic/actions.ts
  client/src/containers/AdvancedSearch/logic/reducer.ts
  client/src/containers/AdvancedSearch/logic/saga.ts
  client/src/containers/AdvancedSearch/logic/state.ts
  client/src/containers/WorkPage/logic/actions.ts
  client/src/services/issue.service.ts
  server/.env.example
  server/config/es.config.ts
  server/docker-compose.yml
  server/package-lock.json
  server/package.json
  server/src/controllers/issue.controllers.ts
  server/src/helpers/issue.helper.ts
  server/src/repositories/issue.repository.ts
  server/src/seeders/1598364447117-ElasticSearch_Issue.ts
  server/src/services/elasticsearch.service.ts
Labels: enhancement, feature

#310 Add showing projects in boards table
  client/src/containers/Boards/index.tsx
  client/src/containers/Boards/styles.module.scss
  client/src/styles/variables.scss
  client/src/typings/webapi.d.ts
  server/src/models/Board.ts
  server/src/models/Result.ts
  server/src/repositories/board.repository.ts
Labels: enhancement

#301 Remove one step from board creation
  client/src/components/BoardModalMenuAlgorithm/index.tsx
  client/src/components/BoardModalMenuType/index.tsx
  client/src/components/BoardModalMenuType/styles.module.scss
  client/src/components/CreateBoardModal/index.tsx
  client/src/typings/boardTypes.ts
Labels: fix

#299 Make filters, boards, projects tables have the same styling
  client/src/components/FilterItem/index.tsx
  client/src/components/FilterItem/styles.module.scss
  client/src/containers/Boards/index.tsx
  client/src/containers/Boards/styles.module.scss
  client/src/containers/Filters/index.tsx
  client/src/containers/Filters/styles.module.scss
  client/src/containers/Projects/index.tsx
  client/src/containers/Projects/styles.module.scss
  client/src/containers/Projects/table.tsx
Labels: fix

#312 Fix issues on schema drop
  server/config/io.config.ts
  server/src/AI/selectUpdateIssueWatchNotificationMessage.ai.ts
  server/src/repositories/issue.repository.ts
Labels: bug, fix

#311 Redirect to advanced search && styled btn
  client/src/containers/Filters/index.tsx
  client/src/containers/Filters/styles.module.scss
Labels: fix, redesign

#313 Load issues on saved filter
  client/src/containers/AdvancedSearch/IssueTable/index.tsx
  client/src/containers/AdvancedSearch/logic/actionTypes.ts
  client/src/containers/AdvancedSearch/logic/saga.ts
Labels: bug, fix

#306 Hotfix/work page styles
  client/src/components/IssueActivityItem/index.tsx
  client/src/components/IssueActivityItem/styles.module.scss
  client/src/components/ManagerAsideBlock/index.tsx
  client/src/components/ManagerWorkBlock/index.tsx
  client/src/components/ProfileAside/index.tsx
  client/src/components/ProfileManager/index.tsx
  client/src/components/ProfileManagerSection/index.tsx
  client/src/components/ProfilePicture/index.tsx
  client/src/components/UserActivityItem/index.tsx
  client/src/components/UserActivityItem/styles.module.scss
  client/src/components/WorkAssignedBlock/index.tsx
  client/src/components/WorkAssignedBlock/styles.module.scss
  client/src/components/WorkIssueCard/index.tsx
  client/src/components/WorkIssueCard/styles.module.scss
  client/src/components/WorkOnBlock/index.tsx
  client/src/components/WorkOnBlock/styles.module.scss
  client/src/components/WorkOnCard/index.tsx
  client/src/components/WorkOnCard/styles.module.scss
  client/src/components/common/ModalViewProject/index.tsx
  client/src/components/common/ModalViewProject/styles.module.scss
  client/src/containers/ProfilePage/index.tsx
  client/src/containers/ProfilePage/styles.module.scss
  client/src/containers/WorkPage/logic/state.ts
  client/src/styles/index.scss
  client/src/styles/variables.scss
  server/src/helpers/emailTemplates.helper.ts
  server/src/repositories/user.repository.ts
  server/src/seeders/1597345244377-Team.ts
Labels: enhancement, fix

#315 Fix updating elastic data
  server/src/controllers/issue.controllers.ts
  server/src/seeders/1598364447117-ElasticSearch_Issue.ts
  server/src/services/elasticsearch.service.ts
Labels: bug, fix

#317 Fix: create filter redirect
  client/src/containers/AdvancedSearch/AdvancedFilters/index.tsx
  client/src/containers/AdvancedSearch/logic/reducer.ts
  client/src/containers/AdvancedSearch/logic/state.ts
  client/src/containers/Filters/index.tsx
  server/.env.example
Labels: enhancement, fix

#316 Feature fix bug/show user only filters
  client/src/components/FilterItem/index.tsx
  client/src/containers/Filters/index.tsx
  client/src/containers/Filters/logic/actionTypes.ts
  client/src/containers/Filters/logic/actions.ts
  client/src/containers/Filters/logic/reducer.ts
  client/src/containers/Filters/logic/saga.ts
  client/src/containers/Filters/logic/state.ts
  client/src/containers/Filters/styles.module.scss
  client/src/containers/Filters/table.tsx
  client/src/containers/SaveFilterModal/logic/saga.ts
  client/src/services/filter.service.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  server/src/controllers/filter.controllers.ts
  server/src/repositories/filter.repository.ts
Labels: bug, enhancement, fix, redesign

#318 Fix sort by priority
  server/src/entity/Priority.ts
  server/src/repositories/issue.repository.ts
Labels: bug, fix

#281 Feature/project labels
  client/package-lock.json
  client/package.json
  client/src/components/ProjectSidebar/config/sidebarItems.ts
  client/src/components/ProjectSidebar/index.tsx
  client/src/components/ProjectSidebar/styles.module.scss
  client/src/components/common/ConfirmModal/index.tsx
  client/src/components/common/Label/index.tsx
  client/src/components/common/Label/styles.module.scss
  client/src/containers/ProjectDetails/form.tsx
  client/src/containers/ProjectDetails/index.tsx
  client/src/containers/ProjectDetails/selectIcon.tsx
  client/src/containers/ProjectLabels/AddLabelModal.tsx
  client/src/containers/ProjectLabels/index.tsx
  client/src/containers/ProjectLabels/logic/actionTypes.ts
  client/src/containers/ProjectLabels/logic/actions.ts
  client/src/containers/ProjectLabels/logic/reducer.ts
  client/src/containers/ProjectLabels/logic/saga.ts
  client/src/containers/ProjectLabels/logic/state.ts
  client/src/containers/ProjectLabels/styles.module.scss
  client/src/containers/ProjectPeople/AddPeopleModal.tsx
  client/src/containers/ProjectPeople/index.tsx
  client/src/containers/ProjectSettings/logic/state.ts
  client/src/containers/Projects/styles.module.scss
  client/src/containers/Projects/table.tsx
  client/src/containers/Routing/index.tsx
  client/src/pages/ProjectSettings/index.tsx
  client/src/redux/rootReducer.ts
  client/src/redux/rootSaga.ts
  client/src/services/projects.service.ts
  client/src/styles/variables.scss
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  client/src/typings/rootState.ts
  client/src/typings/webapi.d.ts
  server/src/controllers/projects.controllers.ts
  server/src/entity/ProjectLabel.ts
  server/src/entity/Projects.ts
  server/src/repositories/projects.repository.ts
  server/src/routes/projects.routes.ts
  server/validators/validateProjectLabel.validator.ts
Labels: enhancement, feature

#319 Added animated notifications count indicator
  client/src/components/NotificationsMenu/index.tsx
  client/src/components/common/NotificationsCount/index.tsx
  client/src/components/common/NotificationsCount/styles.module.scss
  client/src/containers/Header/index.tsx
Labels: enhancement, feature

#321 Fixed eslint and hook
  client/package-lock.json
  client/src/components/common/NotificationsCount/styles.module.scss
  server/package.json
  server/src/entity/Projects.ts
Labels: enhancement, fix, refactoring

#322 Swap breadcrumb and header on kanban board page
  client/src/components/AdvancedSearch/FilterPart/FilterComponents/PriorityFilter.tsx
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/CreateIssueModal/logic/initalState.ts
  client/src/containers/UpdateIssueModal/index.tsx
  client/src/typings/webapi.d.ts
  server/src/models/Issue.ts
  server/src/models/Result.ts
  server/src/repositories/board.repository.ts
Labels: enhancement, fix

#307 Feature/crop avatar
  client/package-lock.json
  client/package.json
  client/src/components/ConfirmPassModal/index.tsx
  client/src/components/CropModal/index.tsx
  client/src/components/CropModal/styles.module.scss
  client/src/components/ProfilePicture/index.tsx
  client/src/components/ProfilePicture/styles.module.scss
  client/src/components/common/Portal/index.tsx
  client/src/containers/ProfilePage/index.tsx
  client/src/containers/ProfilePage/logiс/saga.ts
  client/src/helpers/canvas.helper.ts
  server/config/jwt.config.ts
  server/src/controllers/git.controllers.ts
  server/src/routes/git.routes.ts
  server/src/routes/index.ts
  server/src/seeders/1596645895543-User.ts
  server/src/services/git.service.ts
Labels: enhancement, feature

#323 Hotfix/work page styles
  client/src/components/AccountManager/index.tsx
  client/src/components/EmailManager/index.tsx
  client/src/components/IssueActivityItem/styles.module.scss
  client/src/components/ManagerAsideBlock/index.tsx
  client/src/components/ManagerWorkBlock/index.tsx
  client/src/components/ManagerWorkBlock/styles.module.scss
  client/src/components/ManagerWorkSection/index.tsx
  client/src/components/PasswordCheck/styles.module.scss
  client/src/components/ProfileManager/index.tsx
  client/src/components/ProfilePicture/index.tsx
  client/src/components/ProfilePicture/styles.module.scss
  client/src/components/SecurityManager/index.tsx
  client/src/components/SubmitEmail/index.tsx
  client/src/components/UserActivityItem/styles.module.scss
  client/src/components/WorkAssignedBlock/index.tsx
  client/src/components/WorkAssignedBlock/styles.module.scss
  client/src/components/WorkIssueCard/index.tsx
  client/src/components/WorkIssueCard/styles.module.scss
  client/src/components/WorkOnCard/index.tsx
  client/src/components/WorkOnCard/styles.module.scss
  client/src/components/common/ModalViewProject/index.tsx
  client/src/components/common/ModalViewProject/styles.module.scss
  client/src/containers/WorkPage/logic/state.ts
  client/src/containers/WorkPage/styles.module.scss
  client/src/styles/index.scss
  client/src/styles/mixins.scss
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  server/src/repositories/user.repository.ts
  server/src/seeders/1596645895543-User.ts
Labels: enhancement, fix

#324 Update header styling
  client/src/assets/logo192.png
  client/src/components/IssueActivityItem/styles.module.scss
  client/src/components/ProfileHeader/styles.module.scss
  client/src/components/common/NotificationsCount/styles.module.scss
  client/src/containers/Header/index.tsx
  client/src/containers/Header/styles.module.scss
  client/src/containers/LandingPage/MainPage.tsx
  client/src/containers/LandingPage/styles.module.scss
  client/src/containers/LoginPage/styles.module.scss
  client/src/containers/WorkPage/styles.module.scss
  client/src/styles/index.scss
  client/src/styles/variables.scss
Labels: enhancement

#327 Improvement/load teammate filters && setting favorite filters
  client/src/components/FilterItem/index.tsx
  client/src/containers/Filters/logic/saga.ts
  client/src/containers/Filters/table.tsx
  client/src/services/filter.service.ts
  server/src/controllers/filter.controllers.ts
  server/src/repositories/filter.repository.ts
  server/src/repositories/user.repository.ts
  server/src/routes/filter.routes.ts
  server/src/seeders/1596645895543-User.ts
  server/src/seeders/1597050608478-Filter.ts
Labels: enhancement, fix

#329 Fix filters page
  client/src/containers/Filters/index.tsx
Labels: enhancement, fix, refactoring

#330 Hotfix/work page styles
  client/src/components/ManagerAsideBlock/styles.module.scss
  client/src/components/ProfileAside/styles.module.scss
  client/src/components/ProfilePicture/styles.module.scss
  client/src/components/ProfileSection/styles.module.scss
Labels: enhancement, fix

#332 Hotfix/work page styles
  client/src/components/AccountManager/index.tsx
  client/src/components/CropModal/index.tsx
  client/src/components/CropModal/styles.module.scss
  client/src/components/EmailManager/index.tsx
  client/src/components/IssueActivityItem/index.tsx
  client/src/components/IssueActivityItem/styles.module.scss
  client/src/components/ManagerAsideBlock/styles.module.scss
  client/src/components/ManagerWorkBlock/styles.module.scss
  client/src/components/ProfileAside/styles.module.scss
  client/src/components/ProfileHeader/styles.module.scss
  client/src/components/ProfileSection/index.tsx
  client/src/components/ProfileSection/styles.module.scss
  client/src/components/ProfileTeamBlock/index.tsx
  client/src/components/UserActivityItem/styles.module.scss
  client/src/containers/Header/styles.module.scss
  client/src/containers/LandingPage/styles.module.scss
  client/src/containers/ProfilePage/index.tsx
  client/src/containers/ProfilePage/styles.module.scss
  client/src/containers/WorkPage/styles.module.scss
  client/src/icons/profile/teams.svg
  client/src/styles/index.scss
  client/src/styles/mixins.scss
  client/src/styles/variables.scss
Labels: fix

#334 fix work-page styles
  client/src/components/IssueActivityItem/styles.module.scss
  client/src/components/ProfileActivityBlock/styles.module.scss
  client/src/components/ProjectCard/styles.module.scss
  client/src/components/SubmitedInput/styles.module.scss
  client/src/components/UserActivityItem/styles.module.scss
  client/src/components/WorkOnBlock/index.tsx
  client/src/components/WorkOnCard/index.tsx
  client/src/components/WorkOnCard/styles.module.scss
  client/src/containers/LandingPage/styles.module.scss
  client/src/styles/index.scss
Labels: enhancement, fix

#331 General style fixes
  client/package-lock.json
  client/package.json
  client/src/components/InviteNotification/index.tsx
  client/src/components/NotificationsMenu/index.tsx
  client/src/components/common/NotificationsCount/index.tsx
  client/src/components/common/NotificationsCount/styles.module.scss
  client/src/components/common/UserAvatar/styles.module.scss
  client/src/components/common/UserNotification/index.tsx
  client/src/components/common/UserNotification/styles.module.scss
  client/src/containers/App/App.tsx
  client/src/containers/CreateColumnModal/logic/context.tsx
  client/src/containers/Header/index.tsx
  client/src/containers/Header/styles.module.scss
Labels: enhancement, fix, redesign, refactoring, styles, will update

#335 Moved show all checkbox to bottom
  client/src/components/NotificationsMenu/index.tsx
  client/src/components/common/UserNotification/index.tsx
  client/src/translations/ru.ts
Labels: duplicate, enhancement, fix

#336 Hotfix/work page styles
  client/src/components/BoardsMenu/index.tsx
  client/src/components/FiltersMenu/index.tsx
  client/src/components/ProfileActivityBlock/index.tsx
  client/src/components/ProfileActivityBlock/styles.module.scss
  client/src/components/ProfileAside/styles.module.scss
  client/src/components/ProfileHeader/styles.module.scss
  client/src/components/ProfilePicture/styles.module.scss
  client/src/containers/ProfilePage/logiс/saga.ts
  server/src/controllers/user.controllers.ts
Labels: fix

#338 Fixed update issue modal
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/UpdateIssueModal/index.tsx
Labels: duplicate, enhancement, fix, refactoring, styles

#339 add styles
  client/src/components/PeopleList/PeopleListItem/index.tsx
  client/src/components/PeopleList/PeopleListItem/style.module.scss
  client/src/components/PeopleList/index.tsx
  client/src/components/ProfileTeamBlock/index.tsx
  client/src/components/TeamsList/TeamListItem/index.tsx
  client/src/components/TeamsList/TeamListItem/style.module.scss
  client/src/components/TeamsList/index.tsx
  client/src/components/WorkProjectBlock/index.tsx
  client/src/components/WorkProjectBlock/styles.module.scss
  client/src/containers/LandingPage/styles.module.scss
  client/src/containers/People/index.tsx
  client/src/containers/People/style.module.scss
  client/src/containers/SearchPeopleAndTeamField/index.tsx
  client/src/containers/SearchPeopleAndTeamField/style.module.scss
  client/src/styles/index.scss
  client/src/styles/mixins.scss
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  server/src/repositories/teams.repository.ts
Labels: fix

#340 hotfix reset password
  client/src/components/PeopleList/PeopleListItem/style.module.scss
  client/src/containers/ResetEmail/index.tsx
  client/src/containers/ResetEmail/styles.module.scss
Labels: fix

#341 Feature/project labels
  client/src/components/ProjectSidebar/config/sidebarItems.ts
  client/src/components/common/ConfirmModal/index.tsx
  client/src/components/common/Label/index.tsx
  client/src/components/common/Label/styles.module.scss
  client/src/components/common/Label/useLabelWidth.tsx
  client/src/containers/ProjectLabels/AddLabelModal.tsx
  client/src/containers/ProjectLabels/index.tsx
  client/src/containers/ProjectLabels/styles.module.scss
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  server/src/controllers/projects.controllers.ts
Labels: enhancement, fix

#342 Hotfix/team page
  client/src/components/PeopleList/PeopleListItem/style.module.scss
  client/src/components/ProfileActivityBlock/index.tsx
  client/src/components/ProfileActivityBlock/styles.module.scss
  client/src/components/ProfileSection/index.tsx
  client/src/components/TeamActivity/index.tsx
  client/src/components/TeamDevsCard/index.tsx
  client/src/components/TeamLinks/LinkCard.tsx
  client/src/components/TeamLinks/index.tsx
  client/src/components/TeamLinks/styles.module.scss
  client/src/components/TeamWorkedProjects/index.tsx
  client/src/components/TeamWorkedProjects/styles.module.scss
  client/src/components/TeamsMembersCard/index.tsx
  client/src/components/TeamsMembersCard/styles.module.scss
  client/src/components/UserActivityItem/styles.module.scss
  client/src/components/common/ModalViewProfile/index.tsx
  client/src/components/common/ModalViewProfile/styles.module.scss
  client/src/containers/DefaultPageWrapper/styles.module.scss
  client/src/containers/TeamPage/index.tsx
  client/src/containers/TeamPage/logic/actionTypes.ts
  client/src/containers/TeamPage/logic/actions.ts
  client/src/containers/TeamPage/logic/reducer.ts
  client/src/containers/TeamPage/logic/saga.ts
  client/src/containers/TeamPage/logic/state.ts
  client/src/containers/TeamPage/styles.module.scss
  client/src/services/team.service.ts
  client/src/styles/index.scss
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  server/src/controllers/teams.controllers.ts
  server/src/repositories/projects.repository.ts
  server/src/repositories/user.repository.ts
  server/src/routes/teams.routes.ts
Labels: enhancement, fix

#343 Hotfix/team page
  client/src/components/AccountManager/styles.module.scss
  client/src/components/EmailManager/index.tsx
  client/src/components/EmailManager/styles.module.scss
  client/src/components/ManagerAsideBlock/styles.module.scss
  client/src/components/ManagerWorkBlock/styles.module.scss
  client/src/components/PeopleList/PeopleListItem/style.module.scss
  client/src/components/ProfileHeader/styles.module.scss
  client/src/components/ProfileManager/styles.module.scss
  client/src/components/ProfilePicture/index.tsx
  client/src/components/ProfilePicture/styles.module.scss
  client/src/components/ProfileSection/index.tsx
  client/src/components/ProfileSection/styles.module.scss
  client/src/components/ProjectCard/index.tsx
  client/src/components/ProjectCard/styles.module.scss
  client/src/components/SecurityManager/styles.module.scss
  client/src/components/TeamActivity/index.tsx
  client/src/components/TeamDevsCard/index.tsx
  client/src/components/TeamDevsCard/styles.module.scss
  client/src/components/TeamLinks/index.tsx
  client/src/components/TeamWorkedProjects/index.tsx
  client/src/components/TeamWorkedProjects/styles.module.scss
  client/src/components/UserActivityItem/index.tsx
  client/src/components/UserActivityItem/styles.module.scss
  client/src/components/WorkOnCard/styles.module.scss
  client/src/components/WorkProjectBlock/index.tsx
  client/src/containers/People/index.tsx
  client/src/containers/People/style.module.scss
  client/src/containers/ProfilePage/styles.module.scss
  client/src/containers/ResetEmail/index.tsx
  client/src/containers/ResetEmail/styles.module.scss
  client/src/containers/TeamPage/index.tsx
  client/src/containers/TeamPage/styles.module.scss
  client/src/containers/WorkPage/styles.module.scss
  client/src/styles/index.scss
  client/src/styles/mixins.scss
Labels: enhancement, fix

#344 Advanced-search/Remove useless objects && Style page
  client/src/components/AdvancedSearch/FilterPart/DropdownComponents/TextSearch.tsx
  client/src/components/AdvancedSearch/FilterPart/DropdownComponents/styles.module.scss
  client/src/components/AdvancedSearch/FilterPart/FilterComponents/CommentFilter.tsx
  client/src/components/AdvancedSearch/FilterPart/FilterComponents/index.tsx
  client/src/components/AdvancedSearch/FilterPart/helper.tsx
  client/src/components/AdvancedSearch/HeaderCell/index.tsx
  client/src/components/AdvancedSearch/MoreFilters/index.tsx
  client/src/components/AdvancedSearch/MoreFilters/styles.module.scss
  client/src/components/ContainTextInput/index.tsx
  client/src/components/ContainTextInput/styles.module.scss
  client/src/components/IssueItem/index.tsx
  client/src/components/SearchTitle/FilterOptions/styles.module.scss
  client/src/components/SearchTitle/index.tsx
  client/src/components/SearchTitle/styles.module.scss
  client/src/containers/AdvancedSearch/IssueTable/index.tsx
  client/src/containers/AdvancedSearch/logic/actionTypes.ts
  client/src/containers/AdvancedSearch/logic/reducer.ts
  client/src/containers/AdvancedSearch/logic/saga.ts
  client/src/containers/AdvancedSearch/logic/state.ts
  client/src/containers/AdvancedSearch/styles.module.scss
  client/src/containers/SaveFilterModal/index.tsx
  client/src/containers/SaveFilterModal/styles.module.scss
  client/src/containers/WorkPage/styles.module.scss
  client/src/styles/mixins.scss
  client/src/translations/en.ts
  client/src/translations/ua.ts
  server/src/helpers/issue.helper.ts
  server/src/repositories/issue.repository.ts
  server/src/seeders/1597050485179-FilterDef.ts
Labels: enhancement, redesign

#345 Add Delete Filter
  client/src/components/DeleteFilterModal/index.tsx
  client/src/components/FilterItem/index.tsx
  client/src/containers/Filters/logic/actionTypes.ts
  client/src/containers/Filters/logic/actions.ts
  client/src/containers/Filters/logic/reducer.ts
  client/src/containers/Filters/logic/saga.ts
  client/src/services/filter.service.ts
Labels: enhancement

#347 fix styles people-page
  client/src/components/ProfileActivityBlock/index.tsx
  client/src/components/ProfileHeader/styles.module.scss
  client/src/components/TeamActivity/index.tsx
  client/src/components/TeamDevsCard/index.tsx
  client/src/components/TeamDevsCard/styles.module.scss
  client/src/components/TeamLinks/LinkCard.tsx
  client/src/components/TeamLinks/index.tsx
  client/src/components/TeamLinks/styles.module.scss
  client/src/components/TeamWorkedProjects/index.tsx
  client/src/components/TeamsMembersCard/index.tsx
  client/src/components/TeamsMembersCard/styles.module.scss
  client/src/containers/TeamPage/index.tsx
  client/src/containers/TeamPage/styles.module.scss
  client/src/containers/WorkPage/styles.module.scss
  client/src/styles/index.scss
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
Labels: enhancement, fix

#346 Sort filters table
  client/src/containers/Filters/table.tsx
  client/src/typings/webapi.d.ts
  server/src/entity/Filter.ts
Labels: enhancement

#349 Create input for text search
  client/src/components/AdvancedSearch/FilterPart/DropdownComponents/TextSearch.tsx
  client/src/components/AdvancedSearch/FilterPart/DropdownComponents/styles.module.scss
  client/src/components/AdvancedSearch/FilterPart/DropdownComponents/textSearch.module.scss
  client/src/components/AdvancedSearch/MoreFilters/index.tsx
  client/src/components/AdvancedSearch/MoreFilters/styles.module.scss
  client/src/components/ContainTextInput/index.tsx
  client/src/components/ContainTextInput/styles.module.scss
Labels: enhancement, redesign

#348 Fix/project styles
  client/src/assets/images/double-arrow-left.svg
  client/src/components/ProjectSidebar/index.tsx
  client/src/components/ProjectSidebar/styles.module.scss
  client/src/components/common/Label/index.tsx
  client/src/components/common/Label/styles.module.scss
  client/src/containers/CreateProjectModal/index.tsx
  client/src/containers/CreateProjectModal/styles.module.scss
  client/src/containers/Header/styles.module.scss
  client/src/containers/ProjectDetails/form.tsx
  client/src/containers/ProjectDetails/styles.module.scss
  client/src/containers/ProjectLabels/AddLabelModal.tsx
  client/src/containers/ProjectLabels/index.tsx
  client/src/containers/ProjectLabels/styles.module.scss
  client/src/containers/ProjectPeople/index.tsx
  client/src/containers/ProjectPeople/styles.module.scss
  client/src/containers/ProjectSettings/styles.module.scss
  client/src/containers/Projects/styles.module.scss
  client/src/containers/Projects/table.tsx
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
Labels: enhancement, fix

#350 Fix create label text field empty string validation
  client/src/containers/ProjectLabels/AddLabelModal.tsx
Labels: fix

#351 Fix/scrum board backlog issues display
  client/src/components/Sprint/SprintIssues/index.tsx
  client/src/components/Sprint/index.tsx
  client/src/containers/Filters/table.tsx
Labels: bug, fix

#354 Added the same type icons as on jira
  server/src/seeders/1596719363245-IssueType.ts
  server/src/seeders/1597334747593-Issue.ts
Labels: enhancement, redesign, refactoring

#353 Feature: columns settings
  client/src/components/IssueCommentForm/index.tsx
  client/src/components/IssuePageInfoColumn/index.tsx
  client/src/components/ProjectIssuesColumn/index.tsx
  client/src/components/Sprint/index.tsx
  client/src/containers/.DS_Store
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/Board/Kanban/styles.module.scss
  client/src/containers/Board/index.tsx
  client/src/containers/BoardColumn/logic/actionTypes.ts
  client/src/containers/BoardColumn/logic/actions.ts
  client/src/containers/BoardColumn/logic/saga.ts
  client/src/containers/ColumnsSettingsPage/index.tsx
  client/src/containers/ColumnsSettingsPage/styles.module.scss
  client/src/containers/CreateColumnModal/.DS_Store
  client/src/containers/CreateColumnModal/Body.tsx
  client/src/containers/CreateColumnModal/logic/context.tsx
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/InteractiveColumn/EditForm/index.tsx
  client/src/containers/InteractiveColumn/index.tsx
  client/src/containers/InteractiveColumn/styles.module.scss
  client/src/containers/IssuePageContent/index.tsx
  client/src/containers/ProjectIssuesPage/index.tsx
  client/src/containers/Routing/index.tsx
  client/src/pages/ColumnsSettings/index.tsx
  client/src/pages/IssuePage/index.tsx
  client/src/services/boardColumn.service.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  client/src/typings/webapi.d.ts
  server/src/controllers/boardColumn.controllers.ts
  server/src/entity/BoardColumn.ts
  server/src/models/Board.ts
  server/src/models/Result.ts
  server/src/repositories/boardColumn.repository.ts
  server/src/seeders/1596645901833-Board.ts
Labels: enhancement, feature, refactoring

#355 Add some styles to filters page
  client/src/components/FiltersHeader/index.tsx
  client/src/components/FiltersHeader/styles.module.scss
  client/src/containers/Filters/filters.module.scss
  client/src/containers/Filters/index.tsx
  client/src/containers/Filters/styles.module.scss
  client/src/containers/Filters/table.tsx
  client/src/containers/People/style.module.scss
Labels: redesign

#352 Fix/update modals dimmer
  client/src/components/AddPeopleModal/index.tsx
  client/src/components/ConfirmPassModal/index.tsx
  client/src/components/CreateBoardModal/index.tsx
  client/src/components/CropModal/index.tsx
  client/src/components/DeleteFilterModal/index.tsx
  client/src/components/DeleteUserModal/index.tsx
  client/src/components/Sprint/SprintIssues/styles.module.scss
  client/src/components/TeamAddPeopleModal/aditionalModal.tsx
  client/src/components/TeamAddPeopleModal/index.tsx
  client/src/components/TeamLinks/CreateLink.tsx
  client/src/components/TeamLinks/DeleteLink.tsx
  client/src/components/TeamsMembersCard/RemoveUserModal.tsx
  client/src/components/common/ConfirmModal/index.tsx
  client/src/components/common/SprintModal/CreateSprintModal/index.tsx
  client/src/components/common/SprintModal/DeleteSprintModal/index.tsx
  client/src/components/common/SprintModal/EditSprintModal/index.tsx
  client/src/components/deleteBoardModal.tsx
  client/src/containers/CreateColumnModal/Body.tsx
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/CreateProjectModal/index.tsx
  client/src/containers/CreateTeamModal/index.tsx
  client/src/containers/DeleteIssueModal/index.tsx
  client/src/containers/ProjectDetails/selectIcon.tsx
  client/src/containers/ProjectLabels/AddLabelModal.tsx
  client/src/containers/ProjectPeople/AddPeopleModal.tsx
  client/src/containers/SaveFilterModal/index.tsx
  client/src/containers/UpdateIssueModal/index.tsx
Labels: fix

#356 Changed error message on invite fail
  server/src/controllers/boardColumn.controllers.ts
  server/src/repositories/boardColumn.repository.ts
  server/src/repositories/teammates.repository.ts
  server/src/seeders/1596645901833-Board.ts
Labels: enhancement, fix

#357 Changed 404 page image
  client/src/assets/images/404.png
  client/src/pages/404/styles.module.scss
Labels: enhancement, redesign

#358 Style: notifications
  client/src/components/InviteNotification/index.tsx
  client/src/components/InviteNotification/styles.module.scss
  client/src/components/NotificationsMenu/index.tsx
  client/src/components/common/UserNotification/index.tsx
  client/src/components/common/UserNotification/styles.module.scss
  client/src/containers/Header/styles.module.scss
  client/src/pages/404/styles.module.scss
Labels: enhancement, fix, redesign, refactoring, styles

#360 Hotfix/board modal
  client/src/components/AddPeopleModal/index.tsx
  client/src/components/IssueCard/styles.module.scss
  client/src/components/ProjectCard/styles.module.scss
  client/src/components/SubmitedInput/styles.module.scss
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/Board/Kanban/styles.module.scss
  client/src/containers/BoardColumn/index.tsx
  client/src/containers/BoardColumn/styles.module.scss
  client/src/containers/CreateColumnModal/Body.tsx
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/CreateTeamModal/index.tsx
  client/src/containers/DefaultPageWrapper/index.tsx
  client/src/containers/DefaultPageWrapper/styles.module.scss
  client/src/pages/Boards/index.tsx
  client/src/styles/index.scss
  client/src/styles/mixins.scss
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
Labels: fix

#359 Cant login, forget password modal
  client/src/components/ProfileManager/styles.module.scss
  client/src/components/TeamAddPeopleModal/ResultPeople/index.tsx
  client/src/components/TeamAddPeopleModal/ResultPeople/styles.module.scss
  client/src/components/TeamAddPeopleModal/aditionalModal.tsx
  client/src/components/TeamAddPeopleModal/index.tsx
  client/src/components/TeamAddPeopleModal/styles.module.scss
  client/src/components/TeamLinks/CreateLink.tsx
  client/src/components/TeamLinks/DeleteLink.tsx
  client/src/components/TeamLinks/styles.module.scss
  client/src/components/common/ModalViewProfile/styles.module.scss
  client/src/containers/ForgotPassword/index.tsx
  client/src/containers/ForgotPassword/styles.module.scss
  client/src/containers/LandingPage/MainPage.tsx
  client/src/containers/LandingPage/styles.module.scss
  client/src/containers/Routing/index.tsx
  client/src/containers/TeamPage/styles.module.scss
  server/src/controllers/teammates.controllers.ts
  server/src/services/colorGenerator.service.ts
Labels: styles

#363 Redesign issue page
  client/src/components/IssuePageInfoColumn/config/issueActions.ts
  client/src/components/IssuePageInfoColumn/index.tsx
  client/src/containers/DeleteIssueModal/index.tsx
  client/src/containers/IssuePageContent/SmallEditForm/index.tsx
  client/src/containers/IssuePageContent/SmallEditForm/styles.module.scss
  client/src/containers/IssuePageContent/index.tsx
  client/src/containers/IssuePageContent/styles.module.scss
  client/src/containers/ProjectIssuesPage/index.tsx
  client/src/containers/UpdateIssueModal/index.tsx
Labels: enhancement, fix, redesign, refactoring, styles

#364 fix styles board settings
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/Board/Kanban/styles.module.scss
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/style.module.scss
  client/src/containers/BoardColumn/index.tsx
  client/src/containers/BoardColumn/styles.module.scss
  client/src/containers/ColumnsSettingsPage/index.tsx
  client/src/containers/ColumnsSettingsPage/styles.module.scss
  client/src/containers/DefaultPageWrapper/index.tsx
  client/src/containers/InteractiveColumn/EditForm/index.tsx
  client/src/containers/InteractiveColumn/styles.module.scss
  client/src/pages/Boards/index.tsx
  server/src/controllers/issue.controllers.ts
  server/src/middleware/request.validation.middleware.ts
  server/src/requests/Issue.ts
Labels: fix

#365 add styles to modals
  client/src/components/BoardModalFinal/index.tsx
  client/src/components/ConfirmPassModal/index.tsx
  client/src/components/CreateBoardModal/index.tsx
  client/src/components/DeleteFilterModal/index.tsx
  client/src/components/DeleteUserModal/index.tsx
  client/src/components/TeamAddPeopleModal/aditionalModal.tsx
  client/src/components/common/ConfirmModal/index.tsx
  client/src/components/common/SprintModal/CreateSprintModal/index.tsx
  client/src/components/common/SprintModal/DeleteSprintModal/index.tsx
  client/src/components/common/SprintModal/EditSprintModal/index.tsx
  client/src/components/deleteBoardModal.tsx
  client/src/containers/CreateProjectModal/index.tsx
  client/src/containers/CreateProjectModal/styles.module.scss
  client/src/containers/DeleteIssueModal/index.tsx
  client/src/containers/ForgotPassword/index.tsx
  client/src/containers/ForgotPassword/styles.module.scss
  client/src/containers/ProjectDetails/selectIcon.tsx
  client/src/containers/ProjectLabels/AddLabelModal.tsx
  client/src/containers/ProjectLabels/styles.module.scss
  client/src/containers/ProjectPeople/AddPeopleModal.tsx
  client/src/containers/ProjectPeople/styles.module.scss
  client/src/containers/SaveFilterModal/index.tsx
  client/src/containers/SaveFilterModal/styles.module.scss
  client/src/containers/UpdateIssueModal/index.tsx
Labels: fix

#366 spinner; profile;issue;board
  client/src/components/FilterItem/index.tsx
  client/src/components/FilterItem/styles.module.scss
  client/src/components/IssueItem/index.tsx
  client/src/containers/Boards/index.tsx
  client/src/containers/Boards/styles.module.scss
  client/src/containers/Filters/filters.module.scss
  client/src/containers/Filters/index.tsx
  client/src/containers/People/index.tsx
  client/src/containers/People/style.module.scss
  client/src/containers/ProfilePage/index.tsx
  client/src/containers/Projects/index.tsx
  client/src/containers/Projects/styles.module.scss
  client/src/containers/Projects/table.tsx
  client/src/containers/TeamPage/index.tsx
  client/src/containers/TeamPage/styles.module.scss
  client/src/containers/WorkPage/index.tsx
  client/src/styles/index.scss
Labels: fix

#367 Add doc type to elastic
  server/src/controllers/issue.controllers.ts
  server/src/services/elasticsearch.service.ts
Labels: bug, fix

#368 Fix/elastic add doc type
  server/src/services/elasticsearch.service.ts
Labels: fix

#371 Fix project settings breadcrumbs link from project settings
  client/src/containers/ProjectSettings/config/breadcrumbs.ts
  client/src/containers/ProjectSettings/index.tsx
Labels: fix

#370 Fix collapse button styles
  client/src/components/ProjectSidebar/styles.module.scss
  client/src/containers/ProjectDetails/form.tsx
  client/src/containers/ProjectDetails/styles.module.scss
Labels: fix

#369 Redesign: issue page
  client/src/components/IssueComment/index.tsx
  client/src/components/IssuePageInfoColumn/index.tsx
  client/src/components/ProjectIssuesColumn/index.tsx
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/IssuePageContent/SmallEditForm/index.tsx
  client/src/containers/IssuePageContent/index.tsx
  client/src/containers/ProjectIssuesPage/index.tsx
  client/src/containers/UpdateIssueModal/index.tsx
  client/src/helpers/issueResultToPartialIssue.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  client/src/typings/webapi.d.ts
  server/src/entity/Issue.ts
  server/src/entity/ProjectLabel.ts
  server/src/models/Result.ts
  server/src/repositories/issue.repository.ts
  server/src/requests/Issue.ts
Labels: duplicate, enhancement, feature, redesign, refactoring, styles

#372 Fix elastic
  server/src/controllers/issue.controllers.ts
  server/src/repositories/issue.repository.ts
  server/src/services/elasticsearch.service.ts
Labels: fix

#373 fix styles
  client/src/components/ProjectCard/index.tsx
  client/src/components/TeamDevsCard/styles.module.scss
  client/src/components/TeamsList/TeamListItem/index.tsx
  client/src/components/WorkOnCard/index.tsx
  client/src/components/WorkOnCard/styles.module.scss
  client/src/components/WorkProjectBlock/index.tsx
  client/src/components/common/Spinner/index.tsx
  client/src/components/common/Spinner/styles.module.scss
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/Board/Kanban/styles.module.scss
  client/src/containers/BoardColumn/index.tsx
  client/src/containers/BoardColumn/styles.module.scss
  client/src/containers/ColumnsSettingsPage/index.tsx
  client/src/containers/ColumnsSettingsPage/styles.module.scss
Labels: enhancement, fix, styles

#374 Feature/scrum board sidebar
  client/src/components/ScrumBoardSidebar/config/scrumSidebarItems.ts
  client/src/components/ScrumBoardSidebar/index.tsx
  client/src/components/ScrumBoardSidebar/styles.module.scss
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/style.module.scss
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
Labels: enhancement

#375 Fix/project styles
  client/src/components/ProjectSidebar/styles.module.scss
  client/src/containers/ProjectDetails/form.tsx
Labels: fix

#376 Fix/label tooltip
  client/src/components/common/Label/index.tsx
  client/src/components/common/Label/styles.module.scss
Labels: enhancement, fix

#378 Hotfix/entity color
  client/src/components/Avatar/index.tsx
  client/src/components/ProfileAside/index.tsx
  client/src/components/ProfilePicture/index.tsx
  client/src/components/ProfilePicture/styles.module.scss
  client/src/components/ProjectCard/index.tsx
  client/src/components/ProjectCard/styles.module.scss
  client/src/components/TeamAddPeopleModal/ResultPeople/index.tsx
  client/src/components/TeamAddPeopleModal/ResultPeople/СhosenPeople.tsx
  client/src/components/TeamAddPeopleModal/index.tsx
  client/src/components/TeamsMembersCard/index.tsx
  client/src/components/UserActivityItem/index.tsx
  client/src/components/WorkOnCard/index.tsx
  client/src/components/WorkOnCard/styles.module.scss
  client/src/components/WorkProjectBlock/index.tsx
  client/src/components/common/ModalViewProfile/index.tsx
  client/src/components/common/UserAvatar/index.tsx
  client/src/constants/defaultColors.ts
  client/src/containers/DefaultPageWrapper/index.tsx
  client/src/containers/LoginPage/logic/state.ts
  client/src/containers/ProfilePage/logiс/state.ts
  client/src/containers/ResetPassword/index.tsx
  client/src/containers/SearchPeopleAndTeamField/index.tsx
  client/src/containers/WorkPage/logic/state.ts
  client/src/styles/mixins.scss
  client/src/typings/runTimeFix.ts
  client/src/typings/webapi.d.ts
  server/src/entity/Projects.ts
  server/src/entity/UserProfile.ts
  server/src/models/User.ts
  server/src/repositories/board.repository.ts
  server/src/repositories/filter.repository.ts
  server/src/repositories/projects.repository.ts
  server/src/repositories/teammates.repository.ts
  server/src/repositories/teams.repository.ts
  server/src/repositories/user.repository.ts
  server/src/requests/Project.ts
  server/src/requests/User.ts
  server/src/seeders/1596645895543-User.ts
  server/src/seeders/1597048908491-Project.ts
  server/src/seeders/1597311160202-People.ts
  server/src/seeders/1597345244377-Team.ts
  server/src/seeders/1606645895543-Teams.ts
  server/src/services/colorGenerator.service.ts
Labels: enhancement, fix

#377 Move the 'create label' button to top: center the list of labels
  client/src/containers/ProjectDetails/form.tsx
  client/src/containers/ProjectDetails/styles.module.scss
  client/src/containers/ProjectLabels/index.tsx
  client/src/containers/ProjectLabels/styles.module.scss
Labels: fix

#379 Add new logic for choosing the color of the label text
  client/package-lock.json
  client/package.json
  client/src/containers/ProjectLabels/AddLabelModal.tsx
  client/src/helpers/getContrastColor.ts
Labels: enhancement, fix

#381 Fixed create button
  client/src/containers/Header/styles.module.scss
  client/src/styles/index.scss
Labels: enhancement, fix, styles

#382 Fixed change template button bg
  client/src/styles/mixins.scss
  client/src/styles/variables.scss
Labels: enhancement, fix, styles

#383 Projects page: Fixed links and avatar colors
  client/src/constants/defaultColors.ts
  client/src/containers/Projects/styles.module.scss
  client/src/containers/Projects/table.tsx
Labels: enhancement, fix, styles

#384 Improvement: issue page
  client/src/components/IssueCard/index.tsx
  client/src/components/IssueCard/styles.module.scss
  client/src/components/IssueComment/index.tsx
  client/src/components/IssueCommentForm/index.tsx
  client/src/components/IssueFileInput/index.tsx
  client/src/components/IssueFileInput/styles.module.scss
  client/src/components/IssuePageInfoColumn/index.tsx
  client/src/components/common/TagsInput/styles.module.scss
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/BoardColumn/index.tsx
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/IssuePageContent/SmallEditForm/index.tsx
  client/src/containers/IssuePageContent/index.tsx
  client/src/containers/IssuePageContent/styles.module.scss
  client/src/containers/UpdateIssueModal/index.tsx
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
Labels: enhancement, fix, refactoring, styles, will update

#385 Fix side bar
  client/src/components/ScrumBoardSidebar/config/scrumSidebarItems.ts
  client/src/components/ScrumBoardSidebar/styles.module.scss
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/style.module.scss
Labels: fix

#386 Hotfix/general styles
  client/src/components/InviteNotification/index.tsx
  client/src/components/ProfileAboutBlock/index.tsx
  client/src/components/ProjectCard/index.tsx
  client/src/components/ProjectsMenu/index.tsx
  client/src/components/UserActivityItem/index.tsx
  client/src/components/WorkOnCard/index.tsx
  client/src/components/WorkOnCard/styles.module.scss
  client/src/containers/LoginPage/logic/actionTypes.ts
  client/src/containers/LoginPage/logic/actions.ts
  client/src/containers/LoginPage/logic/reducer.ts
  client/src/containers/ProfilePage/logiс/saga.ts
  client/src/containers/ProjectDetails/form.tsx
  client/src/containers/ProjectDetails/styles.module.scss
  client/src/containers/Projects/styles.module.scss
  client/src/containers/WorkPage/logic/state.ts
  client/src/styles/index.scss
  client/src/styles/mixins.scss
  server/src/repositories/teams.repository.ts
  server/src/repositories/user.repository.ts
Labels: fix

#387 Fixed create issue modal
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/UpdateIssueModal/index.tsx
Labels: enhancement, fix, styles

#388 Fix: kanban board
  client/src/components/IssueCard/index.tsx
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/BoardColumn/index.tsx
  client/src/containers/BoardColumn/styles.module.scss
  client/src/containers/CreateIssueModal/body.tsx
  client/src/styles/mixins.scss
Labels: enhancement, fix, styles, will update

#389 Hotfix/scrum board issues rendering
  client/src/components/Sprint/SprintHeader/index.tsx
  client/src/components/Sprint/SprintIssues/index.tsx
  client/src/components/Sprint/index.tsx
  client/src/components/common/SprintModal/CreateSprintModal/index.tsx
  client/src/components/common/SprintModal/DeleteSprintModal/index.tsx
  client/src/components/common/SprintModal/EditSprintModal/index.tsx
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/logic/actionTypes.ts
  client/src/containers/Board/Scrum/logic/reducer.ts
  client/src/containers/Board/Scrum/logic/saga.ts
  client/src/containers/Board/Scrum/logic/state.ts
  client/src/containers/Board/Scrum/style.module.scss
  client/src/helpers/getIssuesBySearchText.helper.ts
  client/src/helpers/matchIssuesToSprint.helper.ts
  client/src/services/issue.service.ts
  server/src/controllers/issue.controllers.ts
  server/src/entity/Sprint.ts
  server/src/routes/issue.routes.ts
Labels: fix

#390 added ellipsis to kanban board
  client/src/containers/Board/Kanban/index.tsx
Labels: enhancement, fix

#391 Align content
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/style.module.scss
Labels: fix

#392 Scrum board: Fixed sockets + minor fixes
  client/src/components/Sprint/SprintIssues/AssigneeAvatar/index.tsx
  client/src/components/Sprint/SprintIssues/index.tsx
  client/src/components/Sprint/index.tsx
  client/src/hooks/useIO.ts
Labels: enhancement, fix

#393 Fix board settings link
  client/src/containers/Boards/index.tsx
  client/src/hooks/useIO.ts
Labels: enhancement, fix

#394 Feature/burndown chart
  client/package-lock.json
  client/package.json
  client/src/components/BurndownChart/chart.module.scss
  client/src/components/BurndownChart/helpers.ts
  client/src/components/BurndownChart/index.tsx
  client/src/components/ScrumBoardSidebar/index.tsx
  client/src/components/Sprint/SprintHeader/index.tsx
  client/src/containers/Report/config/breadcrumbs.ts
  client/src/containers/Report/index.tsx
  client/src/containers/Report/logic/actionTypes.ts
  client/src/containers/Report/logic/actions.ts
  client/src/containers/Report/logic/reducer.ts
  client/src/containers/Report/logic/saga.ts
  client/src/containers/Report/logic/state.ts
  client/src/containers/Report/styles.module.scss
  client/src/containers/Routing/index.tsx
  client/src/pages/IssuePage/logic/saga.ts
  client/src/pages/ReportPage/index.tsx
  client/src/redux/rootReducer.ts
  client/src/redux/rootSaga.ts
  client/src/services/sprint.service.ts
  client/src/typings/rootState.ts
  client/src/typings/runTimeFix.ts
  client/src/typings/webapi.d.ts
  server/docker-compose.yml
  server/src/controllers/sprint.controllers.ts
  server/src/entity/Issue.ts
  server/src/models/Issue.ts
  server/src/models/Result.ts
  server/src/repositories/issue.repository.ts
  server/src/seeders/1597049103388-Sprint.ts
  server/src/seeders/1597334747593-Issue.ts
Labels: enhancement, feature

#395 Create boardcolumn: Fix value type
  client/src/containers/CreateColumnModal/Body.tsx
Labels: fix

#396 Create issue modal: Fix data value type
  client/src/containers/CreateIssueModal/body.tsx
Labels: fix

#397 Fix types!
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/UpdateIssueModal/index.tsx
Labels: fix

#398 Refresh: issues page
  client/src/components/IssueCard/index.tsx
  client/src/components/IssuePageInfoColumn/index.tsx
  client/src/components/ProjectIssuesColumn/index.tsx
Labels: enhancement, feature

#399 add selectLocation component
  client/package-lock.json
  client/package.json
  client/src/components/ManagerAsideBlock/index.tsx
  client/src/components/ProfileAside/index.tsx
  client/src/components/ProfileManager/index.tsx
  client/src/components/ProfileManager/styles.module.scss
  client/src/components/SelectLocation/index.tsx
  client/src/components/SelectLocation/styles.module.scss
  client/src/components/SubmitedInput/index.tsx
  client/src/components/TeamsMembersCard/index.tsx
  client/src/components/common/ModalViewProfile/index.tsx
  client/src/config/googleApi.config.ts
  client/src/containers/ProfilePage/logiс/state.ts
  client/src/containers/ProjectSettings/logic/state.ts
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  client/src/typings/webapi.d.ts
  server/src/entity/UserProfile.ts
  server/src/helpers/emailTemplates.helper.ts
  server/src/models/User.ts
  server/src/repositories/teams.repository.ts
  server/src/requests/User.ts
  server/src/seeders/1596645895543-User.ts
  server/src/seeders/1597334747593-Issue.ts
Labels: enhancement, feature, fix

#400 fix var name
  client/package.json
  client/src/config/googleApi.config.ts
Labels: fix

#401 Kanban sidebar
  client/src/components/IssueActivityItem/index.tsx
  client/src/components/ProjectCard/index.tsx
  client/src/components/ProjectsMenu/index.tsx
  client/src/components/PublicRoute/index.tsx
  client/src/components/ScrumBoardSidebar/config/scrumSidebarItems.ts
  client/src/components/ScrumBoardSidebar/index.tsx
  client/src/components/UserActivityItem/index.tsx
  client/src/components/WorkOnCard/index.tsx
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/Board/Kanban/styles.module.scss
  client/src/containers/Board/Scrum/config/breadcrumbs.ts
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Boards/index.tsx
  client/src/containers/ColumnsSettingsPage/index.tsx
  client/src/containers/ColumnsSettingsPage/styles.module.scss
  client/src/containers/KanbanBoardSidebar/config/sections.ts
  client/src/containers/KanbanBoardSidebar/index.tsx
  client/src/containers/KanbanBoardSidebar/styles.module.scss
  client/src/containers/ProjectIssuesPage/index.tsx
  client/src/containers/ProjectIssuesPage/styles.module.scss
  client/src/containers/ProjectSettings/config/breadcrumbs.ts
  client/src/containers/Projects/table.tsx
  client/src/containers/Routing/index.tsx
  client/src/pages/ProjectIssuesStrict/index.tsx
Labels: enhancement, feature, refactoring, styles

#402 add fixes to styles
  client/src/components/NotificationsMenu/index.tsx
  client/src/components/ProjectCard/index.tsx
  client/src/components/ProjectCard/styles.module.scss
  client/src/components/SelectLocation/index.tsx
  client/src/containers/CreateColumnModal/Body.tsx
  client/src/containers/Header/index.tsx
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
  server/src/seeders/1597334747593-Issue.ts
  server/src/seeders/1598364447117-ElasticSearch_Issue.ts
Labels: fix

#403 Fix/sort filters
  client/src/components/AdvancedSearch/FilterPart/styles.module.scss
  client/src/components/AdvancedSearch/MoreFilters/styles.module.scss
  client/src/components/SearchTitle/index.tsx
  client/src/components/SearchTitle/styles.module.scss
  client/src/containers/Filters/logic/reducer.ts
  client/src/containers/InteractiveColumn/EditForm/index.tsx
  client/src/containers/SaveFilterModal/index.tsx
Labels: fix, redesign

#404 Fix header links
  client/src/components/BoardsMenu/index.tsx
  client/src/components/FiltersMenu/index.tsx
  client/src/components/ProjectsMenu/index.tsx
  client/src/containers/KanbanBoardSidebar/index.tsx
Labels: enhancement, fix

#405 Fixed header dropdowns width
  client/src/styles/headerDropDown.module.scss
  client/src/styles/index.scss
Labels: enhancement, fix, styles

#406 added project issues sidebar
  client/src/containers/Board/Kanban/index.tsx
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/index.tsx
  client/src/containers/ProjectIssuesPage/index.tsx
Labels: enhancement, feature

#407 Fix seeders and color
  client/src/components/IssueCard/index.tsx
  client/src/containers/KanbanBoardSidebar/styles.module.scss
  server/src/seeders/1597048908491-Project.ts
  server/src/seeders/1597334747593-Issue.ts
Labels: enhancement, feature, fix

#408 Feature/main landing page
  client/src/assets/images/appInformation/kanban.png
  client/src/assets/images/appInformation/projects.png
  client/src/assets/images/appInformation/scram.png
  client/src/containers/Routing/index.tsx
  client/src/pages/AppInformation/index.tsx
  client/src/pages/AppInformation/styles.module.scss
  client/src/translations/ua.ts
Labels: enhancement, feature

#409 Feature/git commits
  client/src/components/IssueCommit/issueCommit.tsx
  client/src/components/IssueCommit/styles.module.scss
  client/src/containers/IssuePageContent/SmallEditForm/index.tsx
  client/src/containers/IssuePageContent/index.tsx
  client/src/containers/IssuePageContent/styles.module.scss
  client/src/services/issue.service.ts
  client/src/styles/mixins.scss
  client/src/typings/runTimeFix.ts
  client/src/typings/webapi.d.ts
  server/package-lock.json
  server/package.json
  server/src/controllers/git.controllers.ts
  server/src/entity/Issue.ts
  server/src/models/Result.ts
  server/src/routes/git.routes.ts
  server/src/services/git.service.ts
Labels: feature, fix

#410 Fixed collapse styles
  client/src/containers/KanbanBoardSidebar/styles.module.scss
  client/src/styles/headerDropDown.module.scss
Labels: enhancement, fix, styles

#411 Fix sidebar render on Reports page
  client/src/components/ScrumBoardSidebar/index.tsx
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Report/index.tsx
  client/src/containers/Routing/index.tsx
Labels: fix

#414 Fix collapse button size
  client/src/components/ScrumBoardSidebar/styles.module.scss
  client/src/containers/KanbanBoardSidebar/styles.module.scss
Labels: fix

#415 Fix bug: elastic data storage and parsing
  server/src/services/elasticsearch.service.ts
Labels: bug, fix

#412 change default git repository
  client/src/components/SelectLocation/index.tsx
  server/src/services/git.service.ts
Labels: fix

#413 Feature/main landing page
  client/src/containers/KanbanBoardSidebar/styles.module.scss
  client/src/pages/AppInformation/index.tsx
  client/src/translations/en.ts
  client/src/translations/ru.ts
  client/src/translations/ua.ts
Labels: enhancement

#416 Fixed a bug when the project name was the maximum number of character…
  client/src/components/ProjectsMenu/index.tsx
  client/src/styles/headerDropDown.module.scss
Labels: fix

#417 Impr/filters
  client/src/components/SearchTitle/FilterOptions/index.tsx
  client/src/components/SearchTitle/FilterOptions/styles.module.scss
  client/src/components/SearchTitle/index.tsx
  client/src/containers/SaveFilterModal/index.tsx
Labels: redesign

#420 Fix Issue seeder
  server/src/seeders/1597334747593-Issue.ts
Labels: fix

#419 Feature/git commits
  client/src/components/InviteNotification/index.tsx
  client/src/components/PeopleList/PeopleListItem/index.tsx
  client/src/components/PeopleList/index.tsx
  client/src/components/ProjectCard/index.tsx
  client/src/components/ProjectCard/styles.module.scss
  client/src/components/WorkProjectBlock/index.tsx
  client/src/containers/Header/index.tsx
  client/src/containers/People/style.module.scss
  client/src/styles/index.scss
Labels: fix

#421 Swap kanban and scram images, add fixed text size
  client/src/pages/AppInformation/index.tsx
  client/src/pages/AppInformation/styles.module.scss
Labels: fix

#423 Feature/git commits
  client/src/constants/GoogleLogin.ts
  client/src/containers/LoginPage/index.tsx
  client/src/containers/LoginPage/logic/saga.ts
  server/src/controllers/auth.controllers.ts
  server/src/entity/UserProfile.ts
  server/src/seeders/1597334747593-Issue.ts
Labels: fix

#424 Fix statuses
  client/src/components/IssueCard/index.tsx
  client/src/components/IssuePageInfoColumn/index.tsx
  client/src/containers/UpdateIssueModal/index.tsx
  server/src/seeders/1597334747592-IssueStatus.ts
  server/src/seeders/1597334747593-Issue.ts
Labels: enhancement, fix, styles

#425 Scrum Board Issues: Remove left and right padding
  client/src/components/Sprint/SprintIssues/styles.module.scss
Labels: fix

#426 Fix/kanban column height flex
  client/src/containers/Board/Kanban/styles.module.scss
  client/src/containers/BoardColumn/index.tsx
  client/src/containers/BoardColumn/styles.module.scss
Labels: fix

#427 Fix can't login
  client/src/containers/ForgotPassword/index.tsx
  client/src/containers/ForgotPassword/styles.module.scss
  client/src/styles/index.scss
  client/src/styles/mixins.scss
Labels: enhancement, fix, styles

#428 Fix colors on login page
  client/src/containers/LandingPage/MainPage.tsx
  client/src/containers/LandingPage/styles.module.scss
Labels: fix

#429 Fix kanban board
  client/src/containers/Board/Kanban/styles.module.scss
  client/src/containers/BoardColumn/index.tsx
  server/src/entity/Issue.ts
  server/src/entity/Projects.ts
Labels: enhancement, fix

#430 Change button to Log In only if email is in DB
  client/src/containers/LoginPage/index.tsx
Labels: fix

#431 Fix limits
  client/src/containers/BoardColumn/index.tsx
  server/src/repositories/board.repository.ts
  server/src/repositories/filter.repository.ts
  server/src/repositories/projects.repository.ts
Labels: enhancement, fix

#434 Improve project issues page
  client/src/components/IssueCard/index.tsx
  client/src/components/ProjectIssuesColumn/index.tsx
Labels: enhancement, fix

#432 Fix/kanban column width
  client/src/containers/Board/Kanban/styles.module.scss
Labels: fix

#433 Delete permissions project settins section
  client/src/components/ProjectSidebar/config/sidebarItems.ts
Labels: fix

#435 Remove Boards/Issues on Project deletion
  server/src/entity/Board.ts
  server/src/entity/ProjectLabel.ts
  server/src/repositories/projects.repository.ts
Labels: bug, fix

#437 Update kanban board styling
  client/src/containers/Board/Kanban/styles.module.scss
  client/src/containers/BoardColumn/styles.module.scss
Labels: fix

#436 Feature/git commits
  client/src/components/IssueCard/index.tsx
  client/src/components/IssueCard/styles.module.scss
  client/src/components/PeopleList/PeopleListItem/index.tsx
  client/src/components/ProjectCard/index.tsx
  client/src/containers/Board/Kanban/styles.module.scss
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/style.module.scss
  client/src/containers/Projects/index.tsx
  client/src/styles/index.scss
  server/src/controllers/board.controller.ts
  server/src/repositories/board.repository.ts
Labels: fix

#438 Feature/active sprint
  client/src/components/CreateBoardModal/index.tsx
  client/src/components/Sprint/SprintHeader/index.tsx
  client/src/constants/defaultScrumBoardColumns.ts
  client/src/containers/Board/Scrum/ActiveSprint/ActiveSprint.tsx
  client/src/containers/Board/Scrum/ActiveSprint/activeSprint.module.scss
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/logic/state.ts
  client/src/containers/Board/Scrum/style.module.scss
  client/src/containers/Boards/logic/actionTypes.ts
  client/src/typings/webapi.d.ts
  server/src/entity/Board.ts
  server/src/models/Result.ts
  server/src/repositories/board.repository.ts
  server/src/repositories/boardColumn.repository.ts
  server/src/seeders/1596645901833-Board.ts
  server/src/seeders/1597334747593-Issue.ts
Labels: enhancement, feature

#439 Feature/active sprint
  client/src/containers/Board/Scrum/ActiveSprint/activeSprint.module.scss
Labels: redesign

#443 Hotfix/final fixes
  client/src/components/InviteNotification/index.tsx
  client/src/components/IssueCommentTextInput/index.tsx
  client/src/containers/Header/index.tsx
  client/src/styles/index.scss
Labels: enhancement, fix

#444 Fix modal closing on scrum board creation
  client/src/components/CreateBoardModal/index.tsx
Labels: bug, fix

#445 Create issue in the sprint add it to default todo column
  client/src/components/Sprint/SprintHeader/index.tsx
  client/src/components/Sprint/index.tsx
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/CreateIssueModal/body.tsx
  client/src/containers/CreateIssueModal/index.tsx
Labels: fix

#447 Fix/board settings remove label
  client/src/components/ScrumBoardSidebar/config/scrumSidebarItems.ts
  client/src/containers/Board/Scrum/index.tsx
  client/src/containers/Board/Scrum/style.module.scss
  client/src/containers/ColumnsSettingsPage/index.tsx
  client/src/containers/InteractiveColumn/index.tsx
Labels: bug, fix

#446 Feature/active sprint: Set completed date && add sprint to issue if create on column
  client/src/components/Sprint/SprintHeader/index.tsx
  client/src/containers/Board/Scrum/ActiveSprint/ActiveSprint.tsx
  client/src/containers/BoardColumn/index.tsx
  server/src/repositories/issue.repository.ts
Labels: enhancement, fix

#451 fix getAllUsers
  client/src/services/user.service.ts
  server/src/controllers/user.controllers.ts
  server/src/repositories/user.repository.ts
Labels: fix

#450 Fix edit issue modal
  client/src/containers/UpdateIssueModal/index.tsx
  client/src/styles/index.scss
Labels: enhancement, fix
